### ISSUE TITLE
Return a gamma size of zero rather than 1

### ISSUE THREAD

**Issue by boppbo** [neutrinolabs/xrdp#1064]
I experienced a bug in gnome-settings-daemon crashing after connecting with xrdp. They fixed the issue, but according to the involved gnome developer the handling in xrdp isn't optimal too.

see https://bugzilla.gnome.org/show_bug.cgi?id=794439#c10

The referenced code file is https://github.com/neutrinolabs/xrdp/blob/devel/xorg/X11R7.6/rdp/rdprandr.c#L207
but I'm not sure it is the only place as I use the original xorg-server in combination with xorgxrdp and not x11rdp.

**Comment by jsorg71** [comment]
It's preferred you use the Xorg driver instead of X11rdp
https://github.com/neutrinolabs/xorgxrdp/blob/devel/module/rdpRandR.c#L177
I can't tell if the bug is only talking about X11rdp or both.

**Comment by boppbo** [comment]
I use the xorg driver. All the logs in the linked bug report occured using the xorg driver

**Comment by benzea** [comment]
It could well be that I referenced the wrong code path in the GNOME bugzilla entry. Fact is, @boppbo is seeing an FPE exception in gsd-color, which means that the gamma as queried from the X server (through mutter) has a size of 1.

**Comment by metalefty** [comment]
@boppbo  Isn't the issue identical to this? https://github.com/neutrinolabs/xorgxrdp/pull/111 If so, the issue is already fixed. We're going to make a new xorgxrdp release v0.2.6 in this month and the fix will be included the next release.

Regarding x11rdp, I'd say "wontfix". x11rdp is replaced by xorgxrdp and we're deprecating x11rdp.
xorgxrdp had the same issue but already fixed. Or do you mean xorgxrdp still have the issue not fixed by neutrinolabs/xorgxrdp#111 ?

**Comment by boppbo** [comment]
Thanks, I try to rebuilt xorgxrdp from devel branch an see if it fixes the issue

**Comment by boppbo** [comment]
Thank you again, that fixed the issue!

**Comment by metalefty** [comment]
Dup of neutrinolabs/xorgxrdp#111.
