### ISSUE TITLE
Does not support UTF-8 clipboard in vnc-any session?

### ISSUE THREAD

**Issue by fcying** [neutrinolabs/xrdp#1133]
Client: Windows 10, mstsc
Host: manjaro, tigervnc 1.8.0, xrdp 0.9.6

I connect via `vnc-any` type to an existing VNC session that I start with `vncserver :2`

When I copying a Chinese string between the server and a client, the clipboard contents are not copied as unicode but ansi with a wrong codepage.

When I connect via `Xvnc` type it work fine.

**Comment by matt335672** [comment]
Hi @fcying 

I'm sorry it's taken a long time to provide an answer for this.

There are two clipboard implementations in xrdp:-

1) There's a basic one built in to VNC which only supports codepage 1252. This is what `vnc-any` uses by default.
2) There's a more complete implementation which supports Unicode provided you run the `xrdp-chansrv` program as part of your session.

To use option 2, you'll need to do the following:-
1) use at least xrdp v0.9.16.
2) Add the line `chansrvport=DISPLAY(n)` to your xrdp.ini section. Use the VNC display number instead of 'n'. So for VNC display 10, the line will be `chansrvport=DISPLAY(10)`
3) Within your session, run `xrdp-chansrv`

As will as Unicode text clipboard support, this will allow you to copy-paste file over the clipboard and redirect drives.

I'm going to mark this issue as closed, but If you reply on this issue I'll be able to help you further.
