### ISSUE TITLE
H264 Graphics Pipeline in XRDP

### ISSUE THREAD

**Issue by antoine-roux** [neutrinolabs/xrdp#1174]
Hello,

I'm wondering if XRDP implements the RDP 8.1 Graphics Pipeline.
I'm trying to use the `/gfx-h264` of FreeRDP but it do not works with a XRDP server :(

In the XRDP source code, I can read some lines about H264 codec, but it appears to be another thing not compatible with FreeRDP. What I understand is that Graphics Pipeline's H264 is not just another codec but another channel. Am I wrong?

From FreeRDP side, I see 3 codecs: NSC, JPEG and RemoteFX
https://github.com/FreeRDP/FreeRDP/blob/59e8b6728799e46455ed0eb93a5291ea87eb464f/libfreerdp/core/capabilities.c#L83-L126

But from XRDP side, there is much more codecs.
https://github.com/neutrinolabs/xrdp/blob/577bd8214f7c39d01964c72cbd9ba3487db65667/common/xrdp_constants.h#L311-L335

This sounds very interesting, but I unable to use them... Can someone tell me how to do?

Thanks,
Antoine

**Comment by blackcrack** [comment]
i have there a link because graphic codec and a community for a free codec , 
take a look :  [ ![av1](https://aomedia.org/wp-content/uploads/2018/02/av1-logo.png)aomedia.org ](https://aomedia.org/)

[!AV1: next generation video – The Constrained Directional Enhancement Filter](https://hacks.mozilla.org/2018/06/av1-next-generation-video-the-constrained-directional-enhancement-filter/)

on Mozilla Hacks, a free codec for web.

best regards
Blacky

**Comment by speidy** [comment]
xrdp doesn't support GFX which should be implemented as virtual channel, hence no official H264 graphics in xrdp. 

The codecs you mentioned is a special implementation (doesn't interoperate with standard RDP clients)

They can be used with NeutrinoRDP client only tho.

**Comment by rkkoszewski** [comment]
Are there any plans to add support for this in xrdp at some point? Or is it just not possible with X?
