### ISSUE TITLE
Release macOS Binaries

### ISSUE THREAD

**Issue by mancoast** [neutrinolabs/xrdp#1243]
cloud compilation convinces trust
see https://github.com/neutrinolabs/xrdp/issues/1242

**Comment by metalefty** [comment]
We don't release any binaries for any OS.

**Comment by metalefty** [comment]
Because the best configuration depends on distributions or OS. Making multiple binaries for each distro is a hard work and we don't have enough resources. Distro packagers knows their distributions can configure xrdp to fit the distro. We rely on distro packagers to find out the best configuration. 

Another reason is OS priority. Read the README, macOS is out of our scope so far. Of course users may try by themselves at their own risk. We accept contributions from macOS users but the priority is always lower then GNU/Linux.

*If* we release binaries, it will be for GNU/Linux. Releasing binary for GNU/Linux have a little chance but there's no chance releasing macOS right now.
