### ISSUE TITLE
Setting up kerberos

### ISSUE THREAD

**Issue by skirriks** [neutrinolabs/xrdp#1328]
Hello!
I can't figure out how to set up kerberos authentification in xrdp. Can anyone point me to instructions on how to configure xrdp to work with kerberos?
Compilled with kerberos support enabled:
xrdp -v
xrdp 0.9.9
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-kerberos

User has valid ticket, but when trying to login always getting the following in xrdp-sesman log:
sesman: error while getting initial credentials in k5_kinit

When compilled without kerberos support FreeIPA users are able to login fine after entering their username/passwd

**Comment by moobyfr** [comment]
Hi

there are several levels where kerberos can be used for several level to 
achieve.

For XRDP:
- xrdp auths the user with kerberos (validation from login/pass to get 
credentials from KDC)
- xrdp use pam which is configured to use kerberos to verify the 
login/pass is valid (same as first , but pam is configured to do it.)

it's the only level you will be able to get Kerberos working. This is 
not a limitation from xrdp, but from RDP  protocol.

The kerberos support available in RDP since 2008 is only used at NLA 
level, to authenticate the *server*. The authentication of the user is 
still "classic", as far as today.

(And for the moment, there is no NLA support for xrdp)

Emmanuel Blindauer

Le 04/04/2019 à 12:35, skirriks a écrit :

**Comment by skirriks** [comment]
Thanx for your answer. This mean that configuring kerberos will not provide any advantages for me since pam works perfectly with entering login & password, but are there any methods or future plans to implement SSO for transparent logins of users to remote desktops?

**Comment by puneet336** [comment]
same issue with me.
I have kerberos token, but still  being prompted to provide username and password , after typing i get 
<img width="232" alt="image" src="https://user-images.githubusercontent.com/5935825/235920176-8d1a7007-edd7-4543-8cf3-51b5c1b67f29.png">

in session and 

sesman: error while getting initial credentials in k5_kinit
sesman: error while getting initial credentials in k5_kinit

on terminal.

**Comment by matt335672** [comment]
@puneet336 - having a kerberos token won't currently provide SSO as we don't support NLA yet.

If you want to use kerberos for authentication (e.g. as part of an Active Directory or FreeIPA domain), it's best to build with PAM support and access your KDC that way.

**Comment by puneet336** [comment]
Thank you for the response, i am having issues with PAM version as well.
Will open a new issue .

**Comment by matt335672** [comment]
I'll close this one - it seems pretty dead.
