### ISSUE TITLE
Cannot open a loggin page between the connection of win10 remonte and Ubuntu server

### ISSUE THREAD

**Issue by huangwb8** [neutrinolabs/xrdp#1434]
Recently I used xrdp to connet my Ubuntu(18.04) server. However, I found no reason why I cann't open it. Here is the installation and status of my xrdp service.
```shell
#install xrdp
sudo apt-get install xrdp

#install vnc4server
sudo apt-get install vnc4server tightvncserver

#install xubuntu-desktop
sudo apt-get install xubuntu-desktop

# write xfce4-session to 'xsession'
echo “xfce4-session” >~/.xsession

# open xrdp server
sudo service xrdp restart

# change some setting: annotat final test and exec rows with #, and add gnome-session to the bottom
sudo vim /etc/xrdp/startwm.sh
```
[![2019-11-01_222902.jpg](https://picture.hwb0307.top/images/2019/11/01/wl6urcn3H8YHeXUS.jpg)](https://picture.hwb0307.top/images/2019/11/01/wl6urcn3H8YHeXUS.jpg)

```shell
# install xorg
sudo apt-get install xorg

# install xfce4
sudo apt-get install xfce4

# change port  & add sfce4
sudo sed -i 's/port=3389/port=3390/g' /etc/xrdp/xrdp.ini
sudo echo xfce4-session >~/.xsession

# restart xrdp
sudo service xrdp restart

# check the status of xrdp
```
[![2019-11-01_223228.jpg](https://picture.hwb0307.top/images/2019/11/01/NCS2Dy35fRDi5U0Y.jpg)](https://picture.hwb0307.top/images/2019/11/01/NCS2Dy35fRDi5U0Y.jpg)

However, when I try to log in by my win10 computer, here is the error:
[![2019-11-01_223420.jpg](https://picture.hwb0307.top/images/2019/11/01/J3eNk4LmCNbAxuhe.jpg)](https://picture.hwb0307.top/images/2019/11/01/J3eNk4LmCNbAxuhe.jpg)
It means that I cannot connect remote server because of unavailable connection.

At the same time, I can confirm:
+ My Ubuntu server is working, and I can connect it with other ways(like SSH or wordpress website in it or ftp and so on)
+ I can ping the adress of my server with address like: lucky.XXX.top, which is the one I use in win10 remote connection
+ I had been open the 3390 port out of firewalk and it works normal
[![2019-11-01_223932.jpg](https://picture.hwb0307.top/images/2019/11/01/eZ674QT3yVuzIL6S.jpg)](https://picture.hwb0307.top/images/2019/11/01/eZ674QT3yVuzIL6S.jpg)

 I had try a lot of methods but useless. It seems everything is OK, but I just cannot open anything even just a loggin page in my win10 computer when trying to do some remote connection. What's going on? ㄟ(▔,▔)ㄏ 

System information:
```
Ubuntu 18.04.3 LTS \n \l
xrdp Version 0.9.5

```

**Comment by matt335672** [comment]
Hi @huangwb8 

For the benefit of other people reading this thread, I believe the dialog you're getting on Windows 10 looks like this in English:-

![dialog](https://user-images.githubusercontent.com/30179339/68038640-587db880-fcc2-11e9-9f19-82dec5306e24.png)

I'm basing this on the numbers 1) 2) 3) which are common to both your dialog and my dialog.

The TCP port 3390 you are using for XRDP is non-standard, but that should be OK provided you request the same port on the client side.

To do that from Windows, you can use lucky.XXX.top:3390 for the server name, instead of just lucky.XXX.top. Are you doing that already?

**Comment by huangwb8** [comment]
Hi, @matt335672
Thanks for your quickly apply!  The picture is exatly the error I met.
Yes, I had try this. Even when I didn't apply the following code to change the port of xrdp
```shell
sudo sed -i 's/port=3389/port=3390/g' /etc/xrdp/xrdp.ini
```
I also had try lucky.XXX.top or lucky.XXX.top:3389. It's the same error appearing. 
That makes me confused, and it may nothing about the port,  I think...o(*￣▽￣*)ブ

**Comment by huangwb8** [comment]
by the way, I also test it in another win10 computer, and they appear the same error, so I believe it's the setting problem of xrdp or something in the Ubuntu server instead of the win10 computer.

**Comment by matt335672** [comment]
Hi @huangwb8 
The error dialog is quite long, but it simply means that the clients are unable to establish a TCP connection to the server using the specified TCP port.

It's useful that you've tried another computer. This means its likely that the problem lies somewhere in the network or on lucky.XXX.top.

You haven't said whether the clients and the server are on the same LAN, or whether TCP routing is being used to reach the server from the clients. If TCP routing is being used, there's the possibility of a firewall between the clients and the server.

It's also possible that there is a firewall on the server which you are unaware of. The `netstat` command you've shown earlier just shows that XRDP is listening on port 3390. It will show the same result if a firewall is also present.

Here are a couple of things for you to try:-
- What is the output of the command `sudo ufw status` on lucky.XXX.top?
- Do you have access to another Linux system on the same LAN as one of the Windows 10 clients? If so you could try the following command to see which TCP ports between 3380 and 3400 are actually reachable over the network:-

```
nmap -p 3380-3400 --open lucky.XXX.top
```

I believe the `nmap` program is also available for Windows, if you don't have another Linux system handy.

**Comment by huangwb8** [comment]
!!!AMAZING!!!
It can not help more!
Apologize for a long time not to return~
You are right! It's exactly the problem of firewall. By `sudo ufw status`, I didn't see 3390/3389 port/tcp opened.Simply, I use 
```shell
sudo ufw allow 3390/tcp
```
Problem solved!
