### ISSUE TITLE
Secure access by default (TLS) vs using a certificate

### ISSUE THREAD

**Issue by albertocastillo2001** [neutrinolabs/xrdp#1446]
Hello

I am currently using XRDP server and by default on xrdp.ini it's set to
crypt_level=high
ssl_protocols=TLSv1.2, TLSv1.3
#tls_ciphers=HIGH

Settingd are mainly by default.

No certificate is specified. However, is still secure to access a server setup like this? can a packet sniffer capture the traffic being sent? Is the information being transferred encrypted or decrypted?

Thanks

**Comment by metalefty** [comment]
There would be two points. xrdp supports two types of encryption. One is classic RDP  encryption that is not very secure now (opportunistic encryption). The other one is TLS that is introduced to replace classic RDP encryption.

You seem to be mixing and misunderstanding these two encryptions. 

This is a configuration for classic RDP encryption. This doesn't affect with TLS at all. You can forget this if you want to use TLS only.

* low: traffic only client -> server will be encrypted with 40bit RC4
* medium: 40bit RC4 for both directions
* high: 128bit RC4 for both directions

```
 crypt_level=high
```

These are configurations for TLS.
```
ssl_protocols=TLSv1.2, TLSv1.3
#tls_ciphers=HIGH
```

You also must prepare a TLS certificate and private key or you cannot use TLS. Specify the place with the following parameters.
```
certificate=
key_file=
```

One more important point is `security_layer`. This controls which classic RDP encryption or TLS to use. `negotiate` is the default value.

* negotiate: negotiate encryption with the client (whichever available TLS or RDP)
* rdp: use only classic RDP connections (not very secure)
* tls: use only TLS, xrdp doesn't accept connections if misconfigured a certificate

```
security_layer=negotiate
```

So if you haven't configured certificates, classic RDP encryption is used instead of TLS because `security_layer` should be set to `negotiate` by default.

To ensure TLS, `set security_layer=tls`.

**Comment by metalefty** [comment]
Close due to no feedback from the reporter.
