### ISSUE TITLE
xrdp-chansrv killed by SIGSEGV

### ISSUE THREAD

**Issue by Shen-Nung** [neutrinolabs/xrdp#1501]
Hello,

xrdp sessions are getting a segmentation fault when disconnecting. - "xrdp-chansrv killed by SIGSEGV". This started after an upgrade from xrdp 0.9.0 to 0.9.12. Server OS is CentOS 7.6 & 7.7. I've tried adjusting a number of xrdp.ini and sesman.ini parameters but the problem persists. xrdp is a mission-critical application for us running on 200 servers, so any help is greatly appreciated.

Clients include MSRDP Windows, MSRDP Mac, Remmina

One significant change we made was changing _security_layer_ from 'RDP' to 'negotiate' and sessions are now setting up via TLS 1.2.

Gary

**Comment by matt335672** [comment]
Could be fixed by #1487 which patches a problem introduced in 0.9.12 related to remote drives.

Are you using EPEL, or building from source?

If you're using EPEL you could try 0.9.11. If you don't have an old copy of an EPEL mirror you'll need to extract it from koji here:-
[https://koji.fedoraproject.org/koji/buildinfo?buildID=1388259](https://koji.fedoraproject.org/koji/buildinfo?buildID=1388259)

If you're building from source, try applying this patch for #1487 to the source tree:-

[https://github.com/neutrinolabs/xrdp/commit/72bece526bb5863d99a52546374c0c3b1561a61a.patch](https://github.com/neutrinolabs/xrdp/commit/72bece526bb5863d99a52546374c0c3b1561a61a.patch)

If that doesn't fix it we'll need to gather more information.

**Comment by metalefty** [comment]
Should be fixed in v0.9.13. If the issue still exists, comment on this. I'll reopen
