### ISSUE TITLE
--localstatedir= Question?

### ISSUE THREAD

**Issue by jradxl** [neutrinolabs/xrdp#1508]
Did you know that "xrdp" always creates a "run" sub-directory below whatever is put in --localstatedir=
So, if I try to run xrdp as a non-root user, and I want the localstatedir=/run/xrdp, then "xrdp" creates
/run/xrdp/run
Now, "xrdp-sesman" doesn't do this and as it has to start first, it thus implies a ExecStartPre script to create "/run/xrdp/run" with correct permissions.
Of course, I could use --nodaemon, but that floods messages into syslog/journalctl

Is this intentional behavour?
Thanks

**Comment by matt335672** [comment]
Morning John,

I've had a trawl through the affected code area histories in xrdp and xrdp-sesman.

The functionality to create the pid directory (localstatedir) was implemented in xrdp in 2012 in commit 62bf3c61f530024284c56a126a407c537220e28f.

At the time, the corresponding feature was not added to sesman.

Back in those days we'll have been using the init.d script to start xrdp services. This script starts xrdp, and then starts xrdp-sesman if required. Arguably there's a race condition here if the localstatedir doesn't exist.

So I think the actual answer to your question is that this isn't intentional behaviour, but is rather historical behaviour.

As to running the xrdp process as a non-root user, it's something I've also given a bit of thought to. It's attractive from a security perspective but has a number of design problems which would need to be solved. A couple are:-

- Unless sesman is also running as non-root (which makes starting sessions challenging), a different localstatedir is probably required. A simple workaround is to start as root and then drop privileges.
- The sockets created by the user's chansrv process need to be connected to when a session is resumed. At the moment xrdp can do this as it's running as root. If it's running as a restricted user, this functionality will not be available. This one's a bit tricky, as connecting to chansrv effectively gives you access to a lot of information available to the session. It's possible these connections needs to be reworked to go in the other direction, but it's not obvious how, or at least not to me.

I hope I've (largely) understood where you're coming from, and that's useful. If you've got any comments on my thoughts above I'd very much like them - I may be missing something obvious.

**Comment by jradxl** [comment]
Hello Matt
Thank you for your detailed and updated answer. And thank you all for the excellent xrdp software which is always my first choice for remote access.

We have somewhat overlapped, as I have been and compiling and installing as root xrdp for many years, and also only just realised Debian/Ubuntu run as a non-root account. Hence my thoughts as to how I could always install your latest build with my own script. See https://github.com/jradxl/xrdp-build-install. (I could of just used the Deb Sources, but was interested in trying myself)

It does seem to work, but I don't know if it's total right yet!

Do you think running xrdp as non-root is more secure, as some of my uses of xrdp are public facing?

Perhaps you could write a quick Wiki entry on how to do it, and perhaps thinking of support this non-root method in the future.

Thanks again
John

**Comment by matt335672** [comment]
Hi John,

I've had a (very) quick look at your script, and it seems to be working along the right lines in that it's doing all the things that the Debian patch seems to do.

The three things that spring to mind that would be difficult for xrdp as non-root are creating the log file, creating the PID file and accessing the sockets dir. I can see you've got the first and third of these covered but not the second (I might have missed it). Is the PID file being created, and does `systemctl stop xrdp` work as expected?

Personally I'm a big fan of only running things as root if they absolutely need to, so I think that this is a worthwhile thing to investigate. However, running any kind of directly-connected internet service which simply uses username/password to authenticate is risky these days. A more secure option would be to set up a jump server facing the internet which you then use to reach the actual target server. You can then use 2FA to authenticate to the jump server before connecting to the target. [guacamole](https://guacamole.apache.org/) [apache.org] might be worth a look for XRDP - it's something I've played with recently. It may, or may not suit your particular use case(s).

The project as a whole has taken a decision not to support running xrdp as non-root directly, but rather to leave this to the distros to patch - see the comments on #464. However, the project is also amenable to patches which aren't intrusive - see neutrinolabs/xorgxrdp#110 . Personally I'm happy with this approach. I really like your idea of a wiki entry however. I'll do some research first so that I'm up to speed with the Debian patch and its implications then I'll knock something up and let you know - I'd appreciate it if you can review it for me.

Thanks for the constructive comments.

**Comment by metalefty** [comment]
Thank you for reporting and as Matt says, it is historical behaviour and worth addressing.

**Comment by matt335672** [comment]
John,

Sorry it's taken a while to get back to you. There turns out to be quite a bit of complexity in the Debian package which I hadn't appreciated.

Could you have a look at these two pages on my local Wiki?

- [https://github.com/matt335672/xrdp/wiki/Running-the-xrdp-process-as-a-non-root](https://github.com/matt335672/xrdp/wiki/Running-the-xrdp-process-as-a-non-root)
- [https://github.com/matt335672/xrdp/wiki/The-socksdir-directory](https://github.com/matt335672/xrdp/wiki/The-socksdir-directory)

I think these cover the detail you need, but I'd really appreciate another couple of eyes to look at them before I add them to the main wiki.

@mirabilos - I've attempted to document some of the excellent work you've done getting the `xrdp` daemon running as non-root  on Debian. I may have some things wrong, so if you've got time to cast your eye over the two local pages above that could be very useful.

Thanks very much

**Comment by jradxl** [comment]
Dear MattThank you so much for writing these two documents, and my apologise for a bit of delay in responding.
They are excellent and catch very succinctly what I perceived the Debian package to do, and helped me understand in greater detail what is necessary to run xrdp as non-root. I just wonder whether the "xrdp process" document would benefit from a final conclusions paragraph, as I am just left wondering whether the Neutrinolabs' team think of this as interesting but unimportant, or whether you will adopt this method.
Linux packages go out of date so easily, that many I'm sure, like me, regularly return to your source code which builds so quickly and easily, but perhaps don't realise xrdp is running as root.
Meanwhile, after thinking this through, I have, on my four hobbyist public VMs from various suppliers, denied access to 3389, and now connect via a SSH tunnel.
I had no idea it was so that was so easy to set that up using Remmina.
Thanks again, and I look forward to seeing them published!And thanks again for the Xrdp software - I wish I had the brain to understand even half of it!
Best wishes in these strange virus avoiding times...John

    On Monday, 23 March 2020, 17:32:11 GMT, matt335672 <notifications@github.com> wrote:  
 
 


John,

Sorry it's taken a while to get back to you. There turns out to be quite a bit of complexity in the Debian package which I hadn't appreciated.

Could you have a look at these two pages on my local Wiki?
   
   - https://github.com/matt335672/xrdp/wiki/Running-the-xrdp-process-as-a-non-root
   - https://github.com/matt335672/xrdp/wiki/The-socksdir-directory

I think these cover the detail you need, but I'd really appreciate another couple of eyes to look at them before I add them to the main wiki.

@mirabilos - I've attempted to document some of the excellent work you've done getting the xrdp daemon running as non-root on Debian. I may have some things wrong, so if you've got time to cast your eye over the two local pages above that could be very useful.

Thanks very much

**Comment by matt335672** [comment]
Hi John,

Your message was very timely - I'd just remembered I needed to chase this up!

The pages are moved to the main Wiki now. I can see where you're coming from as regards a 'final conclusions' paragraph, and if this was a commercial environment rather than an open source project I'd certainly add it, particularly as security is becoming more and more important. I'm just a contributor here however, and I'm not going to rock any boats.

Tunnelling over ssh is a great idea if you've got a decent connection - if you've got the ssh port open anyway you're in no way increasing the attack surface, and it's so beautifully simple. The only real disadvantage of this approach that I can see is the 'TCP over TCP' problem, so if the connection is flaky you might have to consider more sophisticated approaches.

Thanks for the kind words, and best wishes to you too,

-- 
Matt
