### ISSUE TITLE
Use the software keyboard on the login screen.

### ISSUE THREAD

**Issue by tanakakz-alpha** [neutrinolabs/xrdp#1510]
I want to use a software keyboard to enter the ID / PW when logging in from a client without a keyboard (such as a smartphone or tablet).

**Comment by metalefty** [comment]
And what?

**Comment by metalefty** [comment]
I think it's client stuff. 

![image](https://github.com/neutrinolabs/xrdp/assets/941609/530711b3-21c8-4de2-b2de-46d68c33a57a)

**Comment by metalefty** [comment]
An iPhone RDP client (Microsoft official) can use screen keyboard.

**Comment by tanakakz-alpha** [comment]
I never use an iPhone.
The client's software keyboard covers or shrinks the screen, making it difficult to navigate input fields.
I would like to see this functionality provided on the server side.

**Comment by metalefty** [comment]
iPhone client is just an example, same with Android.

**Comment by metalefty** [comment]
It's your choice not to use an iPhone, but the applications mentioned here are also available on Android and have almost the same functionality. It doesn't matter if you never use an iPhone. It's just an example to take a screenshot.

Whether the software keyboard is implemented on client side or server side, it covers the screen to show the keyboard because the dimension of the screen is limited.　Something's to be shrunk or covered to show something on the same screen.

I don't think it is difficult to navigate input field. The client app has a mouse-mode, using the smartphone's screen like a touchpad It also can be navigated by tab keys on the client-side screen keyboard. 

https://github.com/neutrinolabs/xrdp/assets/941609/81312ed8-fb28-471a-85e8-53cc5e59ce97

**Comment by tanakakz-alpha** [comment]
I use guacamole and that's the only option for my clients. When I start Guacamole's software keyboard, the screen becomes very small, making it difficult to even select input fields.
I need a software keyboard that is client-independent and can be operated within the screen.

**Comment by tanakakz-alpha** [comment]
Not everyone has a choice of client software. I want a software keyboard that can be used uniformly on the server side.

**Comment by metalefty** [comment]
I'm afraid we currently have enough resources to implement such rare use case with multiple workarounds. 

* Some clients have software keyboard
* Login screen is not the only way to input username and password

To be honest, it is not worth time and effort implementing it with our limited resources at the moment. However, it's opensource. We dev team would not implement it by ourselves but will be happy to merge if someone implement well-designed, meet software keyboard. It's the OSS way!

If you think your suggestions may be useful to more than just yourself, it is worth for you to work on. 

I always welcome and wait you contribution!  Thanks for your suggestion.

**Comment by tanakakz-alpha** [comment]
I respect decisions not to implement due to low priority.
However, please know that some people may need this feature.

**Comment by metalefty** [comment]
Thanks for understanding.

Someone needs to write code to make things happen. We are happy to merge. Regarding this feature, we dev team would not be the someone however please remember everyone can be someone!
