### ISSUE TITLE
Raspbian channel 3: open failed: connect failed: Connection refused

### ISSUE THREAD

**Issue by Sathware** [neutrinolabs/xrdp#1523]
I have installed xrdp on my raspberry pi using this guide: http://c-nergy.be/blog/?p=6020. However, whenever I add "address=127.0.0.1" in the 'global' section of xrdp.ini and try to connect. Windows remote connection comes up with an error saying "An internal error has occurred" and in the pi's terminal I get "channel 3: open failed: connect failed: Connection refused", but it works fine if i don't add "address=127.0.0.1"

**Comment by matt335672** [comment]
Hi @Sathware 

That guide is pretty old now. It refers to a version of Ubuntu that is 5-and-a-half years old, and which came with XRDP 0.6.1.

To deal with your immediate question, `address=` in xrdp.ini is not supported on versions of XRDP >=v0.9.11. Instead it's been folded in to the `port=` setting. **You haven't told us which version of XRDP you're using, and a lot hinges on that.**

For more modern versions, if you want to limit XRDP to listening on the local machine only, use `port=tcp://.:3389` instead of `port=3389`. This is documented in xrdp.ini if it is supported.

For all versions of xrdp, you can use the `ss` command to see what port and address xrdp is listening on.

If you're listening on all interfaces:-

```
$ sudo ss -nlp '( sport = :3389 )'
Netid  State    Recv-Q   Send-Q      Local Address:Port     Peer Address:Port   
tcp    LISTEN   0        2                 0.0.0.0:3389          0.0.0.0:*       users:(("xrdp",pid=2703,fd=11))
```

Just listening on 127.0.0.1:-
```
$ sudo ss -nlp '( sport = :3389 )'
Netid  State    Recv-Q   Send-Q      Local Address:Port     Peer Address:Port   
tcp    LISTEN   0        2               127.0.0.1:3389          0.0.0.0:*       users:(("xrdp",pid=2675,fd=11))
```

A wider question to ask, is "do you still need to do this?" XRDP >= v0.9.1 now supports TLS, which the older version of XRDP did not. This may be adequate to meet your use-case without tunnelling over ssh. It may not of course - if you're coming in over the internet you may prefer the improved security which an ssh tunnel can offer.

Does that answer your question, or have I misunderstood where you're coming from?

**Comment by Sathware** [comment]
I'm using xrdp version 0.9.9-1, sorry i should've been more specific.

**Comment by Sathware** [comment]
The problem doesn't occur if I use putty instead of powershell, so this isn't a problem with xrdp, thank you for the help so far.
