### ISSUE TITLE
xrdp.ini cannot prefill username or password with a "!" (maybe other chars, too)

### ISSUE THREAD

**Issue by cocoon** [neutrinolabs/xrdp#153]
I have the problem that I cannot use password or usernames with a ! in xrdp.ini.

Example 1 (you can see the ! is not visible in the inputfield and it cuts of at the position of the first !):

```
[xrdp1] 
name=sesman-X11rdp
lib=libxup.so
username=askMyuser!name!
password=askMyPassword!
ip=127.0.0.1
port=-1
xserverbpp=24
code=10
```

or

```
[xrdp1] 
name=sesman-X11rdp
lib=libxup.so
username=Myuser!name!
password=MyPassword!
ip=127.0.0.1
port=-1
xserverbpp=24
code=10
```

**Comment by cocoon** [comment]
What about using hashes instead of plaintext passwords?
Would solve this and you wouldn't have plaintext passwords in files.

**Comment by metalefty** [comment]
I'll take this almost 3-year-old issue.

**Comment by metalefty** [comment]
Escaping by backslash shouldn't work because xrdp doesn't treat backslash specially.
I tried to implement the base64 idea. Working for me.

@cocoon 
If you're still interested in this, can you test my prefill-credentials branch?
https://github.com/metalefty/xrdp/tree/prefill-credentials

If username or password, write it in base64 format with "{base64}" prefix. It will be passed properly.

```
username=ask{base64}YmFzZTY0                    
password=ask{base64}YmFzZTs2NCFwYXNzd29yZCM=
```

```
username={base64}YmFzZTY0
password={base64}YmFzZTs2NCFwYXNzd29yZCM=
```

**Comment by cocoon** [comment]
Hey thanks for all those fixes, you're on fire! Sorry I was on training, so had no time to check.
I am indeed interested and will try it!

**Comment by cocoon** [comment]
Tried it already and yes it is working great! Thanks!

**Comment by metalefty** [comment]
Merged.
