### ISSUE TITLE
Session reconnection not working

### ISSUE THREAD

**Issue by FedKey45** [neutrinolabs/xrdp#1566]
Users are rarely able to reconnect to the same session resulting in dozens of sessions.
The port setting in xrdp.ini was set -1. I changed it to ask so users could enter the port of their session and force a reconnect. However this procedure always fails with the error password failure even though the password is correct.

xrdp.ini
[Xvnc]
name=Xvnc
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=ask
#xserverbpp=24
#delay_ms=2000

xrdp-sesman.log
[20200504-10:41:01] [DEBUG] xrdp_wm_log_msg: VNC started connecting
[20200504-10:41:01] [DEBUG] xrdp_wm_log_msg: VNC connecting to 127.0.0.1 5916
[20200504-10:41:01] [DEBUG] xrdp_wm_log_msg: VNC tcp connected
[20200504-10:41:01] [DEBUG] xrdp_wm_log_msg: VNC security level is 2 (1 = none, 2 = standard)
[20200504-10:41:01] [DEBUG] xrdp_wm_log_msg: VNC password failed
[20200504-10:41:01] [DEBUG] VNC error before sending share flag
[20200504-10:41:01] [DEBUG] VNC error before receiving server init
[20200504-10:41:01] [DEBUG] VNC error before receiving pixel format
[20200504-10:41:01] [DEBUG] VNC error before receiving name length
[20200504-10:41:01] [DEBUG] VNC error before receiving name
[20200504-10:41:01] [DEBUG] xrdp_wm_log_msg: VNC error - problem connecting
[20200504-10:41:01] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:42730)
[20200504-10:41:01] [DEBUG] xrdp_wm_log_msg: some problem
[20200504-10:41:01] [ERROR] xrdp_wm_log_msg: Error connecting to: 127.0.0.1
[20200504-10:41:01] [DEBUG] xrdp_mm_module_cleanup
[20200504-10:41:01] [DEBUG] VNC mod_exit

**Comment by matt335672** [comment]
Hi @FedKey45 

I don't think what you are trying will work. The VNC password is not the same as the user password. It is a randomly generated value and the users won't know this.

You can bodge your way round this by getting your users to `ssh` in, and then setting their VNC passwords to known values with the `vncpasswd` command. They'll need to specify the path to the VNC file being used in the `~/.vnc` directory.

This is not however a satisfactory state of affairs, and I think we're better off working on solving the main problem you've described.

Currently with VNC, to reconnect to a session, the requested geometry and colour depth from the RDP client must **exactly** match the geometry and colour depth of the target session.

If your users are connecting from machines with differing physical setups, they'll need to make sure they specify these geometries manually, rather than using full screen, or whatever.

We're aware this is a limitation, and we're working on fixing this so that VNC sessions can be resized.

In the meantime, you could also consider the following possibilities. These could however both involve a bit of effort on your part:-
- Using the Xorg backend which also supports resizing of sessions.
- If you have the resources to build xrdp from scratch, using the pre-release version which supports VNC resizing (see #1343)

I hope that's useful. Please come back to me if you've got any questions.

**Comment by FedKey45** [comment]
Hi matt335672,

So tried your suggestions and I noticed that I indeed connect to a different session when switching color depths.
However the users keep default settings, meaning 24bit color depth and 1080 x 1920 geometry. The same as is set on the target. Yet when the source IP changes or the take their computer out of the docking station, they are unable to connect to the same session.

Will try the pre-release version and let you know the results.

**Comment by matt335672** [comment]
Could you also check in `/etc/xrdp/sesman.ini` that the "session allocation policy" is set to "Default":-

```
Policy=Default
```

If not, it may be causing the behaviour you describe above.

**Comment by FedKey45** [comment]
Yes the policy is still set to default.

Users get a session when using the laptop as a standalone device and a session when using the laptop in a docking with external monitor(s) attached. 

So I have changed my xrdp file and added code=1 to the [Xvnc] section. I will have some users test it.

**Comment by matt335672** [comment]
With time allowing, we're working on getting the enhanced VNC support into the development version. The one you've got has a few rough edges which need to be addressed - any change will be announced in #1343.

I suspect the reason you're getting the extra sessions is that the extra monitors look like a bigger screen to the vanilla XRDP, and so you're ending up with two sessions. A `ps -ef` should show you what the `Xvnc` session geometry is, or you can use `xdpyinfo | grep -i dim` from the session.

In any case, I suspect when you get the hang of the resizable sessions you won't want to go back anyway.
