### ISSUE TITLE
Feature request - separate config file for xrdp and sesman

### ISSUE THREAD

**Issue by jkeltz** [neutrinolabs/xrdp#1588]
I install xrdp on 100's of hosts.  I have a config file directory that is automatically duplicated to all the systems in my department.  My /etc/xrdp is replaced by [config dir]/xrdp, but since the directory is the same everywhere, I then lose the ability to customize my installation because [config dir] is the same on every system.  On certain systems, I need changes in just the sesman.ini file.  I would like xrdp-sesman to be able to accept on the command line a "-c" option for config file.  In this way, I could have [config dir]/xrdp/sesman.ini.[host].  My systemd start script for xrdp-sesman could start with the host-specific config if one was available, or the default otherwise.  This is what I do with most other software packages.  However, xrdp doesn't offer the "-c" option on daemon startup.  It would be nice to put this into xrdp and xrdp-sesman.  
Thanks for your consideration.

**Comment by derekschrock** [comment]
Couldn't you just symlink the host-based conf. to xrdp.ini or sesman.ini?

**Comment by jkeltz** [comment]
The configuration system (which I inherited)  duplicates the configuration  tree on every host, so I can't.  If I change it on one system then it would be reverted.  That's why being able to specify the configuration file on startup would be perfect.
On May 21, 2020, at 11:12 p.m., Derek Schrock <notifications@github.com<mailto:notifications@github.com>> wrote:

Couldn't you just symlink the host-based conf. to xrdp.ini or sesman.ini?

**Comment by matt335672** [comment]
I think this could be quite a handy feature, particularly for testing - I could have made use of it very recently.

I have a look when I get a mo', if no-one else already has.

**Comment by matt335672** [comment]
I've had a look at this, and the obvious thing is to add a `-c` option to xrdp and sesman so that the main config file for these two programs can be overridden.

Two less obvious implications are:-
- The `sesrun` tool needs the same argument. The other tools should probably need it too, but at the moment they have other ways to find `sesman`.
- The xrdp daemon also reads `sesman.ini` to get the port to connect to sesman.  This override will not be available for xrdp, so if you're using this facility sesman will need to be listening on the standard port.

If anyone's not happy with that, please say something.
