### ISSUE TITLE
Xrdp Slow

### ISSUE THREAD

**Issue by gamersalpha** [neutrinolabs/xrdp#1600]
Hello there, 

i m just installa frech install of ubuntu 20.04 and update evrything i just install 
sudo apt_get install xrdp

so i can connect on my virtual machine got to issue very bad :

- No sound
- and the acess is very slow

can u help me to fix this please

**Comment by matt335672** [comment]
Hi @gamersalpha 

- sound: the distro xrdp doesn't include the pulseaudio drivers, so you'll need to follow the procedure we've already discussed in #1564 I'm happy to help you with that if you want to try it.
- slow:  You've not given us a lot to go on. What are you trying to achieve exactly?  Running a remote desktop over a network is never going to be as quick as running locally. 

If you're trying to use a console login at the same time as a remote login on any version of 20.04, read this [wiki page](https://github.com/neutrinolabs/xrdp/wiki/Debian-dbus-user-session-package).

**Comment by gamersalpha** [comment]
Hello there, 
so i try again, i get smooth moving windows is slow

so i m on windows and i connect in rdp to my linux machine ubuntu  20.04 desktop

**Comment by matt335672** [comment]
Hi @gamersalpha 

Are you saying that just dragging Windows about on the desktop is slow?

That doesn't sound like normal behaviour. What kind of network have you got between the two machines? Are they on the same LAN? Are you running wired or wireless?

**Comment by ehaughee** [comment]
I'm having a similar issue with input lag, choppy rendering, etc.  I am on the same LAN (both wired).  What other information would be helpful?

Ubuntu 20.04
KDE Plasma 5.18.5
xrdp 0.9.12

**Comment by matt335672** [comment]
Hi @ehaughee 

That sounds like a bandwidth or latency issue, or possibly packet drops. Are you running a graphically intensive application?

First thing to do would be to establish the available bandwidth and latency between the server and the client, with the server sending. I can't stress enough that it's worth measuring this rather than just assuming all is OK with the link, and you're getting the advertised link speed at both ends.

Measure bandwidth with iperf3. If you can it's best to stop xrdp and reuse its port to make sure packets are traversing host firewalls in the same way. So, on the server:-
- `sudo systemctl stop xrdp`
- `iperf3 -s -p 3389`

On the client:-
- `iperf3 -c <hostname> -p 3389 -R`

On a wireless connection here I get around 52Mb/s from a cheap Windows laptop. That's going through two virtual routers (all on the same site).

Latency (i.e. round-trip-time) can be measured by using ping from the windows side. I'm getting single-digit milliseconds.

That's not a great link, but it's absolutely fine for running software development tools.

Measure the actual bandwidth being used by xrdp by using 'iftop'. So once you've stopped iperf3, restarted xrdp and get a session going, you can use a command like this to look at the throughput in Mb/s :-

```
sudo iftop -f "port 3389"
```

That'll give you a clear idea of exactly what capacity is available on the link, and what xrdp is demanding from it.

**Comment by ehaughee** [comment]
@matt335672 thanks for the cool measuring tips!

Below are my measurements.

**Ping from Windows --> Ubuntu**
```
>ping 192.168.1.12 -n 20

Pinging 192.168.1.12 with 32 bytes of data:
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64
Reply from 192.168.1.12: bytes=32 time<1ms TTL=64

Ping statistics for 192.168.1.12:
    Packets: Sent = 20, Received = 20, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

**iperf output**
```
❯ iperf3 -c 192.168.1.12 -p 3389 -R
Connecting to host 192.168.1.12, port 3389
Reverse mode, remote host 192.168.1.12 is sending
[  5] local 172.20.105.65 port 43828 connected to 192.168.1.12 port 3389
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   112 MBytes   938 Mbits/sec
[  5]   1.00-2.00   sec   107 MBytes   900 Mbits/sec
[  5]   2.00-3.00   sec   112 MBytes   941 Mbits/sec
[  5]   3.00-4.00   sec   112 MBytes   939 Mbits/sec
[  5]   4.00-5.00   sec   110 MBytes   919 Mbits/sec
[  5]   5.00-6.00   sec   112 MBytes   939 Mbits/sec
[  5]   6.00-7.00   sec   110 MBytes   921 Mbits/sec
[  5]   7.00-8.00   sec   112 MBytes   940 Mbits/sec
[  5]   8.00-9.00   sec   112 MBytes   940 Mbits/sec
[  5]   9.00-10.00  sec   107 MBytes   901 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.08 GBytes   930 Mbits/sec   88             sender
[  5]   0.00-10.00  sec  1.08 GBytes   928 Mbits/sec                  receiver

iperf Done.
```

**iftop**
I opened Firefox and dragged the settings window around a bunch.
```
cum:    284MB   peak: 71.5Mb  rates: 69.9Kb  40.5Kb  7.68Mb
RX:    3.57MB          859Kb         7.30Kb  1.74Kb  99.5Kb
TOTAL:  288MB         72.3Mb         77.2Kb  42.3Kb  7.78Mb
```

**Comment by matt335672** [comment]
Thanks for the comprehensive reply!

There doesn't seem to be anything wrong with your network, so that's a good start.

If I'm reading your numbers right (and I'm not entirely sure about that), you're using around 10% of the link bandwidth for the session. Depending on the round-trips needed for communication, this could be suffering from latency. I can't see anything else here which would account for it.

What backend are you using? Xorg or Xvnc?

Xorg can be a bit tricky to set up. If you're using it. see https://github.com/neutrinolabs/xrdp/issues/1026#issuecomment-502302768 and try the settings there.

**Comment by ehaughee** [comment]
I am using Xorg.  I tried setting the connection speed to LAN and I already had the color depth set to 32 bit.  I still see the same lag.  Here is a video showing the input, rendering, and animation lag with LAN+32bit: https://www.dropbox.com/s/zzyqi4l13espvyn/input-lag.mp4?dl=0

I checked that the video (and the uploaded version played in the browser) accurately depicts the input lag I'm seeing (window lags behind the cursor) and the animation lag (clicking log out).  The slowness is not an artifact of video compression.  I have tested with direct access to the "remote" machine (monitor, keyboard, and mouse plugged in to the physical box) and do not see the same latencies.

**Comment by matt335672** [comment]
Hi @ehaughee 

Maybe the video's not doing your user experience justice, but that doesn't look entirely unexpected.

The cursor is drawn locally, the mouse move is sent to the remote end and the remote end updates the screen and sends it back. That looks like a fairly high res screen you've got there to me (is it 2160p?), with a fairly nuanced backdrop. You're going to be sending a lot of data for each redraw, and that will explain the delay.

You could try using a single colour backdrop for the remote session. Areas of a single colour pretty much compress to nothing,  and that will reduce bandwidth and hence round-trip-times.

Other than that, I can't think of anything else which would improve on that experience I'm afraid.

**Comment by ehaughee** [comment]
The monitor is 1080p.  If this is the best performance I can get from a local connection, that's fine, just wanted to make sure there wasn't something else I could do.

For anyone else following along, I ended up turning off the KDE Plasma compositor (System Settings/Display and Monitor/Compositor) which helped a little but obviously disabled things like animations and transparency for the theme I was using.  This is fine for my use-case but may not be for others.

Thanks, @matt335672, for your help!

**Comment by marcsosduma** [comment]
After doing a lot of research, I got good performance with these settings:

xfce4
xorgxrdp-glamor
In /etc/xrdp/sesman.ini and /etc/xrdp/xrdp.ini:

Policy=UBDI
max_bpp=16
xserverbpp=16
use_compression = yes
crypt_level=none
KillDisconnected=true
DisconnectedTimeLimit=0
tcp_send_buffer_bytes=4194304
Tweak for TCP (2x request buffer size):

sudo sysctl -w net.core.wmem_max=8388608
see https://github.com/neutrinolabs/xrdp/issues/1483

Disable compositor:

xfconf-query -c xfwm4 -p /general/use_compositing -t bool -s false
