### ISSUE TITLE
checking malloc return value

### ISSUE THREAD

**Issue by Safari77** [neutrinolabs/xrdp#168]
if you run out of memory in xstream_new, you get segfault, because init_stream dereferences pointer returned by g_malloc without checking for NULL.

**Comment by metalefty** [comment]
I'm not sure where's the issue what you talking about but @proski made lots of memory fixes over the past year. Perhaps this has already been fixed.

**Comment by proski** [comment]
The issue is not fixed. The result of `make_stream()` is not checked anywhere. If it fails to allocate memory, the code will crash.

That said, I don't feel it's a compelling issue. It memory is so short that a few kilobytes cannot be allocated, the program is not likely to work properly. Also, it's easy to write incorrect code for handling memory allocation failures, and it's hard to test such code. Such code itself takes space in memory.

One possible improvement would be to log the out-of-memory condition and then terminate the process. If we have a single malloc wrapper, we can perfection it as much as we want.

**Comment by metalefty** [comment]
Pointer should be provided.
