### ISSUE TITLE
login fails when kerberos ccache is not found

### ISSUE THREAD

**Issue by mikhailnov** [neutrinolabs/xrdp#1715]
xrdp 0.9.13.1 is built with `--enable-kerberos`. Any authnetication under a local non-kerbrized user fails with error message "login failed for display". strace log shows that the last error is an attempt to access not existing `/tmp/krb5cc_0`. It is what a standard MIT libkrb5 function does. Probably its exit code is treated incorrectly in xrdp. A fallback to non-kerberos authentication must be done in such case.

Rebuilding xrdp with `--disable-kerbeos` solves this issue, but then krb authentication will not work. It would be nice if both cases worked.

**Comment by matt335672** [comment]
Hi @mikhailvov

You are right in that the Kerberos module currently just performs standard KRB5 authentication and does not fall back.

On most (but not all) modern systems, the best way to achieve what you are trying to do is to use PAM authentication and authorization so that system manager is responsible for configuring these features. Is that something you'd be interested in exploring? Or is there some reason why you haven't gone down this route?

**Comment by mikhailnov** [comment]
Do you suggest to configure PAM to perform Kerberos authentication? But how should it work, I can't imagine? What is the current workflow to use Kerberos in xrdp?

**Comment by matt335672** [comment]
Yes - that's right.

If you build XRDP with PAM support, it will consult `/etc/pam.d/xrdp-sesman` for authentication authorization and session management. This file can either be customised just for XRDP, or it can include other files used by other services.

You can configure a PAM module `pam_krb5.so` within the PAM stack for XRDP to authenticate Kerberos users and configure `pam_unix.so` to authenticate local users.

More sophisticated possibilities are possible. If your Linux machines are joined to an Active Directory domain you can use `pam_sss.so` rather that `pam_krb5.so` which gives you a lotmoe options

**Comment by mikhailnov** [comment]
Yes, thanks, I know how to configure PAM to authenticate using Kerberos and in a domain. What I do not understand is: does all this mean that a user will still see an xrdp's window with login prompt and will enter a login and password of domain user into it? If xrdp is built with `--enable-kerberos`, the same is done, right?

If yes, then `--enable-kerberos` does not make much sense, because PAM can do any needed authentication.

I thought that a local kerberos ticket can be used to log into an xrdp server without entering a login and password in xrdp's window.

**Comment by matt335672** [comment]
I've just had a trawl through the Kerberos code. It's been a while since I used the krb5 API directly, but from what I can tell, all that it is doing is validating the username and password which is entered, the same as PAM would do.

The authentication interface for xrdp is very simple at the moment (although we're working on improving it). Selecting `--enable-kerberos` doesn't change much in the way of behaviour - it just selects which module is compiled in to validate the username and password.

I can't find any evidence of code in the Kerberos module which would allow a ticket to be used to authenticate or a TGT to be forwarded at the moment.

So I think you're right that that `--enable-kerberos` doesn't make much sense if you've got PAM available. I don't know of any distros that don't have PAM available now, but if I remember correctly, PAM only became an option for Slackware relatively recently.

Is that useful?

**Comment by mikhailnov** [comment]
Thanks. I am sure that all multi-purpise Linux distros and other UNIX-like systems do have PAM on which xrdp can be eun do use PAM.
Current name of this build option is confusing and xrdp is built without it in most or all distros, maybe it makes sense to drop not used and tested code or rename this build option to a name which would reflect that it _replaces_ PAM with kerberos-only authentication.

**Comment by matt335672** [comment]
Slackware's the only Linux or Unix distro I know of which supports a desktop and [until recently](https://slackblogs.blogspot.com/2020/05/slackware-is-now-pamified.html) didn't support PAM.

Given it's only 6 months since Slackware moved in this direction, it's probably a bit soon to remove this entirely. I can try to clarify the wording in `configure.ac` around this.

Have you had a chance to get PAM working the way you want in your setup?

Thanks.

**Comment by matt335672** [comment]
As another note for this thread, OpenBSD does not support PAM, so this module is still needed for these configurations.

**Comment by mikhailnov** [comment]
@metalefty thanks for improvements, it is clearer now.

> Have you had a chance to get PAM working the way you want in your setup?

@matt335672 No, I did not try it because I never wanted to authenticate in xrdp as a domain user, but I am sure it will work if PAM works correctly.
