### ISSUE TITLE
Two clients connect to the same session

### ISSUE THREAD

**Issue by Jackobama** [neutrinolabs/xrdp#1717]
Can the windows proxy in xrdp support two clients to connect to the same session?

**Comment by matt335672** [comment]
If you mean 'two clients at the same time', I don't think the RDP protocol allows for it.

The VNC protocol may provide what you're looking for. Could you provide more info on what you're trying to do?

**Comment by Jackobama** [comment]
> If you mean 'two clients at the same time', I don't think the RDP protocol allows for it.
> 
> The VNC protocol may provide what you're looking for. Could you provide more info on what you're trying to do?


Thank you for your enthusiastic answer. The function I want to do is to use the neutrinordp module to connect to windows resources, and at the same time a client can connect to xrdp to monitor the last connected session image.

**Comment by matt335672** [comment]
I don't think that can be done with XRDP. You'll need to look at other remote control options I'm afraid.

**Comment by Jackobama** [comment]
> I don't think that can be done with XRDP. You'll need to look at other remote control options I'm afraid.

Thank you very much for your answer. I am trying to modify the XRDP code to implement this function. Can you give me some ideas or suggestions?

**Comment by matt335672** [comment]
It's not an area I'm that familiar with. However, I don't believe that XRDP maintains a complete copy of the screen buffer anywhere.

To do this at the XRDP level you'd need to interpret the RDP data stream (documented in [[MS-RDPBCGR]](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/5073f4ed-1e93-45e1-b039-6e30c385867c)) to construct a screen buffer, and then somehow provide access to that.

It's a lot of work and I can't recommend approaching your problem in this way. You're essentially implementing most of an RDP client.

Easier solutions would involve working at the server end or the client end rather than in the middle.

**Comment by Jackobama** [comment]
> Easier solutions would involve working at the server end or the client end rather than in the middle.

Thank you very much for answering my questions all the time. I will seriously consider your suggestions to me. Thank you from the bottom of my heart.

**Comment by matt335672** [comment]
Let me know if you have any other questions. I'll close this issue in a few days if I don't hear from you.

**Comment by Jackobama** [comment]
> Let me know if you have any other questions. I'll close this issue in a few days if I don't hear from you.

Thanks for helping me on the project! I really appreciate it!
