### ISSUE TITLE
i3wm wizard crashes part way through vis xRDP session

### ISSUE THREAD

**Issue by sshaikh** [neutrinolabs/xrdp#1721]
When starting for the first time the i3 window manager runs a wizard that generates a config file for further use.

This wizard fails to create a complete config when invoked via an xRDP session, demonstrating the same behaviour as described here: https://github.com/i3/i3/issues/2141#issuecomment-198514698.

Elsewhere in that issue this is attributed to an `xkb_keymap_key_get_syms_by_level returned no symbols for keycode` error. However the keys that i3 is looking for (the arrow keys) work fine in normal usage. In fact when the file is created correctly (eg by running i3-wizard locally) the now complete config works fine in an xRDP session.

Perhaps related is a behaviour where the media keys on my keyboard are being captured as letter keys, for example pressing mute types the letter "d". This is also confirmed by xev as the same code as pressing the d key.

**Comment by matt335672** [comment]
**Edit 2024-08-12: This isn't quite right. See below.**

I've worked out what's going on here.

For versions 0.9.x and 0.10.x of xrdp, `base` rules are used exclusively by `xorgxrdp` rather than `evdev` rules. It looks like `i3` still doesn't handle this correctly (i3/i3#2141 is still open and I've tried 4.23-52), and so the problem still persists. So for these versions, there's no workaround I can see.

The rest of this post refers to the `devel` version of xrdp.

For the `devel` version of `xrdp`, we've made the XKB rule set configurable at run-time. There is, however, one place where `base` is still used, and that's when the X server is started.

When we start a session, we don't necessarily know what keyboard mappings the RDP client will be using. Indeed, if we're running a session from `xrdp-sesrun` there may not even be a client! So an X server is currently started with base rules, us layout, pc104 model.

When the RDP client connects, we send over rules, model and layout based on the client. These are loaded using XKB, and provided everything listens to the X server keymap events, everything is OK.

It seems to me that `i3-config-wizard` doesn't pick up on the keymap events when the client connects. As a result, it's stuck with the base us pc104 keyboard. I can see this from the logging, where keycode 116 is mapped to 0xffec XK_Super_R (base mapping) rather than 0xff54 XK_Down (evdev mapping). If I kill the wizard and re-run it, it loads the current (evdev-based) keyboard mapping, and all is well.

Using `xvfb-run` is a useful way to query the keycode mapping:-

<pre>
$ xvfb-run --auto-servernum --server-args="-noreset" bash -c 'setxkbmap -rules <b>base</b> -model pc104 -layout us ; xmodmap -pk' | grep 116
    116    	0xffec (Super_R)	0x0000 (NoSymbol)	0xffec (Super_R)
$ xvfb-run --auto-servernum --server-args="-noreset" bash -c 'setxkbmap -rules <b>evdev</b> -model pc104 -layout us ; xmodmap -pk' | grep 116
    116    	0xff54 (Down)	0x0000 (NoSymbol)	0xff54 (Down)	
</pre>

If the session is started by a client connection to xrdp, the remapping to the correct keyboard happens almost straight away - the X server is started, sesman validates the X server is running, starts the `i3` session, and then tells the RDP client to connect to the session. So there's a race between `i3` and the RDP client. Using this `~/.xsession` file for starting i3 works fine with `xrdp` devel:-

```
#!/bin/sh

cd
sleep 1
exec i3 >i3.log 2>&1
```

The rules set can be set to `base`, in which case the existing v0.9.x and v0.10.x behaviour is preserved.

I don't really know what the best way to proceed here is. If `i3` supported `base` rules, we could just use these. Also if the wizard picked up the keymap events, this wouldn't happen either. If we defaulted to `evdev` rather than `base` when the X server is started, this would probably work a lot better (certainly for keyboards similar to `us` `pc104`). We may do this when we've got more user feedback on the `evdev` migration.

An added complication is that FreeBSD also now uses `evdev` rules rather than `base` rules, so i3/i3#2141 may not even be fixed now.

@sshaikh - assuming you remember this, do you have any thoughts on the above?

**Comment by sshaikh** [comment]
Thanks for the follow up! I've been running the same desktops since then so haven't seen the wizard since. Happy to test any fixes but otherwise unless it's a fix that will being value during normal sessions it won't really affect me personally.

**Comment by matt335672** [comment]
Thanks.

I'm minded to close this, after making a note on the xorgxrdp repository that we need to consider moving the default Xorg keyboard rules to evdev to cover rare edge cases like this. At the moment we don't have enough information on the success (or otherwise) of the evdev migration to do that.

**Comment by matt335672** [comment]
I've had another look at the way the keyboard is configured for xorgxrdp.

It seems I'd started the migration from `base` to `evdev` but only done half a job. In particular, there's a structure `g_kbdMap` which still contains `base` keycodes. Further digging shows this structure isn't in fact used(!), but there are differences in the way the keyboard mapping is set between initialisation and a client connection.

In any case, I have a working prototype which fixes this issue completely for `xorgxrdp` on `devel`'. I'll do some more testing and raise a PR.
