### ISSUE TITLE
Any Doc updates to Debian/Ubuntu Build Instructions - xrdp referenced there is v .0.9.4

### ISSUE THREAD

**Issue by bmullan** [neutrinolabs/xrdp#1730]
Just looking at this:  **https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8**

> These are steps for building **xrdp 0.9.4 and xorgxrdp 0.2.4, on debian 8 (jessie)** systems.
> 
> This process is confirmed to be working on 09.10.2017 on **Ubuntu-Gnome 16.4.1**.

Are there changes to the Build process to be aware of?

thanks
brian

**Comment by matt335672** [comment]
Hi Brian,

The link you've got also has:-

```
And also with versions XRDP_VER=0.9.14 and XORG_XRDP_VER=0.2.4 on Ubuntu 16.04.7.
```

At the moment 0.9.14 is the latest released version so there are no problems there.

I take it you're targetting a later version of Ubuntu/Debian or a derivative of it? Off the top of my head there should be no reason why there should be changes for Ubuntu at least.

Are you asking because you're having problems, or are you contemplating a build?

Thanks.

**Comment by matt335672** [comment]
Brian - did you get anywhere with this?

Do you need more help, or can I close this?

Thanks
