### ISSUE TITLE
Xrdp crash after login or stuck in black screen [User still logged in on console] [Solution]

### ISSUE THREAD

**Issue by Pierluigi2497** [neutrinolabs/xrdp#1734]
I've tried to make working xrdp on Kali Linux without success for 3 days,
I used using Kali linux with Xfce4 installed and i've tried also gnome, searching in various log i didnt found what i need
After several attempt, i found the solution

----Before log into an xrdp session, log out or create another user and log into this last one.----

I don't know if someone alredy posted an solution like this, if so delete this post

**Comment by matt335672** [comment]
Hi @Pierluigi2497 

Thanks for your input.

What was the user name you couldn't log in with?

**Comment by Pierluigi2497** [comment]
For these 3 days, i've tried to log with "kali" user but the problem isn't the user itself.
The problem is that i've not logged out from the server before connecting in.
This is my 2° time approccing with rdp and then i dont know how these types of connection work.
I made this Issue just to inform who have the same my problem, how to solve it

**Comment by matt335672** [comment]
Ah, OK I see. Thanks.

Later versions of systemd set up a 'session dbus' for the user which is shared between the local graphical display and ssh sessions, etc. This works well until you log in an XRDP session with the same user, as most desktops don't like sharing the session dbus.

One workaround, which you've found, is to use different users for remote and local sessions.

If you want to use the same user locally and remotely at the same time there may be a way, since Kali is based on Debian. The situation for Debian and derivatives is documented [here](/neutrinolabs/xrdp/wiki/Debian-dbus-user-session-package) on the wiki. This page might help you to get XFCE working, but not GNOME.

I've changed the title of your issue slightly which may make it easier for others to find when searching.

Let me know if you'd like any more info.
