### ISSUE TITLE
Do not spit on the console 2nd stage (inspired by Debian)

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#1762]
Thank you for all of your contributions, @aquesnel, especially logging improvement.

I would like to share some basic directions about logging on the console.

As Debian's downstream patch expresses, they don't like xrdp spit logs on the console when it runs as daemons. I agree with Debian guys at this point. 
* https://salsa.debian.org/debian-remote-team/xrdp/-/blob/master/debian/patches/shutup-daemon.diff

It is partially done in #1142. I would like to complete this. Here's my thoughts about logging:

1. `xrdp` and `xrdp-sesman` should not write anything on stdout/stderr when they run as daemons (except fatal errors)
2. information such as configuration summaries can be dumped when it runs in the foreground

Any feedback is welcome, thanks.

Thoughts:

I personally would like to pick downstream patches up and merge proactively if they're useful to everyone. Because I'm an upstream developer and also a distro package maintainer. Upstream first is a good strategy in most cases. Less downstream patches should make both upstream and downstream happy.

**Comment by aquesnel** [comment]
hi @metalefty ,

Thanks for asking for my opinion.
I agree with you about only logging fatal messages to the console when running as a daemon. I also agree that configuration being dumped to the console when not running as a daemon is a good idea.

I looked at the Debian patch that you linked to, and I don't think it should be applyed it as is because it unconditionally removes useful debugging information. I think that xrdp should conditionally output that information if the user asks for it or create a config that downstream maintainers can define a default for their distribution to disable the information.

I think that a solution based on the logging config will have the biggest impact because as I continue to migrate to the logging to the unified macros across the whole code base then not writing to the console will just follow the configuration.

My ideas for addressing this issue are:
* set the default log level for the console to error or fatal 
* or, when running as a daemon conditionally set the default log level for the console to error or fatal, and if the not running as a daemon then leave the console default to info.
* or, add a command line parameter to enable dumping the config to the console on start up

**Comment by matt335672** [comment]
Hi both,

I added an additional member `dump_on_start` to `struct log_config` as part of #1711. At the moment this is used to suppress dumping the logging output to stdout when running a console utility like `sesrun` which is (I think) exactly what you're trying to do here. It doesn't currently have an easy way to set it in other circumstances.

I was going to suggest using this, but on the other hand I think it might be best to remove it entirely.

If I take @aquesnel's suggestions above as a starting point, this gives the following outline implementation:-

- Remove `dump_on_start` from `struct log_config`
- Add an extra boolean argument to `log_start()` to dump the logging config (`log_start()` is only used by `xrdp` and `xrdp-sesman`)
- Plumb in an extra command-line parameter to `xrdp` and `xrdp-sesman` to allow the boolean value to be changed from whatever the default is.
- Update the man pages for `xrdp` and `xrdp-sesman`

Maybe roughly an hour's work with review time on top.

Does that sound like it's along the right lines? In particular @aquesnel, is it compatible with what you see as the future direction of logging?

**Comment by aquesnel** [comment]
hi both,

Yes @matt335672 , I agree with your suggested outline.

My plans for logging are to continue the logging macro unification work that I started in #1633 and to add more detailed trace logging like what I've done in #1742. So the changes here are compatible with the work I'm doing.
