### ISSUE TITLE
Configure xrdp on Ubuntu 20.04

### ISSUE THREAD

**Issue by mahmoodn** [neutrinolabs/xrdp#1854]
Hi
By setting `port=tcp://:3389`, I see the following netstat output
```
$ sudo netstat -tulpn | grep xrdp
tcp        0      0 0.0.0.0:3389            0.0.0.0:*               LISTEN      9320/xrdp
tcp6       0      0 ::1:3350                :::*                    LISTEN      6051/xrdp-sesman

```
However, from my windows machine, I am not able to connect and returns error in the `initiating remote connection...`.
What else should I check? Maybe still the daemon doesn't receive the request.

**Comment by matt335672** [comment]
@mahmoodn 

Here are some pointers for you:-
- Leave `sudo tail -f /var/log/xrdp.log` running and then try to connect. If you get output that will show whether you're getting through or not.
- Are you running a firewall? What does `sudo ufw status` tell you?

**Comment by mahmoodn** [comment]
Please see below:
```
$ sudo ufw status
[sudo] password for mahmood:
Status: inactive
$ ps aux | grep xrdp
root        6051  0.0  0.0  24436   508 ?        S    Apr 04   0:00 /usr/sbin/xrdp-sesman
xrdp        9320  0.0  0.0  24564   612 ?        S    Apr 04   0:00 /usr/sbin/xrdp
mahmood    63171  0.0  0.0  20544  2804 pts/2    S+   14:45   0:00 grep --color=auto xrdp
```
But as you can see, nothing is recorded when I try to connect to the server.

![image](https://user-images.githubusercontent.com/11626212/113696248-08cec800-96d2-11eb-90f2-082e07a8f341.png)

**Comment by matt335672** [comment]
It looks like there's a name resolution or connectivity error here. If you had managed to reach the Ubuntu machine you'd have more in the log than that.

Can you get a command line up on the Windows machine and ping the hostname you're trying to connect to? Without a firewall, ping should work. Check the IP address displayed by ping is the same on your Ubuntu machine with `ip addr` on the Ubuntu side.

**Comment by mahmoodn** [comment]
Yes I can ping that. However, the IP address assigned on the Ubuntu interface is an internal IP (172.20.54.10). There is an entry in the department firewall/router that maps an external IP to 172.20.54.10. We use the external IP from abroad and I am able to ping and ssh to the machine.

**Comment by matt335672** [comment]
The most likely thing in that case is that the departmental firewall which is NATting to your 172.20.0.0/16 address is not allowing TCP port 3389, which would be standard procedure. You should check with them.

If that's the case and they won't open TCP/3389 (they shouldn't frankly), you can still make use of the ssh port if you've got PuTTY installed on your Windows machine, and you're able to make an ssh connection to your Ubuntu machine.

The idea is to set up a tunnel over ssh so that you can connect to a local port which then gets forwarded over ssh to the remote Ubuntu machine. It's best not to use TCP/3389 for the local port as Windows itself may be listening on it. Use TCP/3390 instead. Procedure is:-

- Make sure you can use PuTTY to get to your Ubuntu machine from your Windows machine. Save the session settings you need to do this.
- While you're logged out, go to the `Connection/SSH/Tunnels` settings, and add a forward from local port 3390 to 3389 on your target machine. It'll look something like this, where `<target>` is the hostname or IP address of your external IP:-
   ```
   L3390    <target>:3389
   ```
- Log in to the machine again over ssh using PuTTY.
- On the Windows machine, run MSTSC.EXE and connect to `localhost:3390`

If all is well, PuTTY will tunnel the TCP connection for you, and you'll be able to log in graphically using xrdp.

**Comment by matt335672** [comment]
@mahmoodn - do you need any more help with this?

**Comment by mahmoodn** [comment]
I didn't get a clear answer from my department if the port is opened or not! So, I wasn't able to go further. For now, I will close the topic. Thanks for your help.
