### ISSUE TITLE
Support Unicode Keyboard events in xrdp

### ISSUE THREAD

**Issue by MagicStarTrace** [neutrinolabs/xrdp#1990]
xrdp: A Remote Desktop Protocol server.
Copyright (C) Jay Sorg 2004-2014
See http://www.xrdp.org for more information.
Version 0.9.5

In the same environment of Chinese and related dependencies, vnc is a device that can bring external Chinese into the remote ubuntu 18.04 system

I currently use the input method in ubuntu, but I hope that the Chinese from the external client can be brought into the ubuntu system

-----------------------------------------------------
apt install -y language-pack-zh-hans   fonts-droid-fallback ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-ukai fonts-arphic-uming

**Comment by matt335672** [comment]
Hi @huyifanstar 

I don't understand what you are trying to do.

Are you trying to get a Chinese keyboard mapping working on the xrdp session? Or are you trying to get the whole locale transferred from the client to the server?

**Comment by MagicStarTrace** [comment]
> Hi @huyifanstar
> 
> I don't understand what you are trying to do.
> 
> Are you trying to get a Chinese keyboard mapping working on the xrdp session? Or are you trying to get the whole locale transferred from the client to the server?

I hope that the Chinese input from the mac client (rdp client) can be transparently transmitted to the remote instance on the mac through the client

**Comment by metalefty** [comment]
@matt335672 The feature he wants is called "Unicode input" / "[Unicode Keyboard Events"](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/551b9903-8fb9-4d00-b3ac-a187431efb86) that the client sends inputs as Unicode characters rather than scan codes. See also #441. xrdp partially supports it. It is possible to type ASCII characters in Unicode mode but further uses are not supported because the inputs are transmitted from xrdp to Xorg as keystrokes via virtual keyboard. We need to invent direct passing of Unicode characters to Xorg/Xvnc to implemtnt it.

Android/iOS RDP clients support it. Also, macOS RDP client support it since last year.
<img width="405" alt="スクリーンショット 2021-09-10 14 03 13" src="https://user-images.githubusercontent.com/941609/132802277-478be559-ec22-45e9-a293-8c041d12198f.png">


It will work like this.

https://user-images.githubusercontent.com/941609/132803539-a07b289f-5bcf-4062-8d0a-7a80ff28d068.mov

**Comment by MagicStarTrace** [comment]
> @matt335672 The feature he wants is called "Unicode input" / "[Unicode Keyboard Events"](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/551b9903-8fb9-4d00-b3ac-a187431efb86) that the client sends inputs as Unicode characters rather than scan codes. See also #441. xrdp partially supports it. It is possible to type ASCII characters in Unicode mode but further uses are not supported because the inputs are transmitted from xrdp to Xorg as keystrokes via virtual keyboard. We need to invent direct passing of Unicode characters to Xorg/Xvnc to implemtnt it.
> 
> Android/iOS RDP clients support it. Also, macOS RDP client support it since last year.
> <img alt="スクリーンショット 2021-09-10 14 03 13" width="405" src="https://user-images.githubusercontent.com/941609/132802277-478be559-ec22-45e9-a293-8c041d12198f.png">
> 
> It will work like this.
> 
>  RPReplay_Final1631250814.mov

Convert Unicode characters to Xorg/Xvnc , Is there any way I can configure it to enable support?
Configuration file ?

Thank You

**Comment by metalefty** [comment]
> t is possible to type ASCII characters in Unicode mode but further uses are not supported because the inputs are transmitted from xrdp to Xorg as keystrokes via virtual keyboard. We need to invent direct passing of Unicode characters to Xorg/Xvnc to implemtnt it.

You didn't read here.

**Comment by matt335672** [comment]
Thanks for the explanation.

@huyifanstar - I'm going to change the title of this issue to reflect @metalefty's comments above.

**Comment by huyifanstar** [comment]
> @matt335672他想要的功能称为“Unicode 输入”/“ [Unicode 键盘事件”](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/551b9903-8fb9-4d00-b3ac-a187431efb86)，客户端将输入作为 Unicode 字符而不是扫描码发送。另见#441。xrdp 部分支持它。可以在 Unicode 模式下键入 ASCII 字符，但不支持进一步使用，因为输入是通过虚拟键盘作为击键从 xrdp 传输到 Xorg 的。我们需要发明将 Unicode 字符直接传递给 Xorg/Xvnc 来实现它。
> 
> Android/iOS RDP 客户端支持它。此外，macOS RDP 客户端从去年开始支持它。
> <img alt="スクリーンショット 2021-09-10 14 03 13" width="405" src="https://user-images.githubusercontent.com/941609/132802277-478be559-ec22-45e9-a293-8c041d12198f.png">
> 
> 它会像这样工作。
> 
>  RPReplay_Final1631250814.mov
![image](https://user-images.githubusercontent.com/15685376/132833832-3b080049-98d7-4ff4-976f-82b0886947e7.png)

Adjusted to Unicode on mac, just tried it, it did not meet expectations
Is there any progress in this area?

**Comment by MagicStarTrace** [comment]
> @matt335672 The feature he wants is called "Unicode input" / "[Unicode Keyboard Events"](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/551b9903-8fb9-4d00-b3ac-a187431efb86) that the client sends inputs as Unicode characters rather than scan codes. See also #441. xrdp partially supports it. It is possible to type ASCII characters in Unicode mode but further uses are not supported because the inputs are transmitted from xrdp to Xorg as keystrokes via virtual keyboard. We need to invent direct passing of Unicode characters to Xorg/Xvnc to implemtnt it.
> 
> Android/iOS RDP clients support it. Also, macOS RDP client support it since last year.
> <img alt="スクリーンショット 2021-09-10 14 03 13" width="405" src="https://user-images.githubusercontent.com/941609/132802277-478be559-ec22-45e9-a293-8c041d12198f.png">
> 
> It will work like this.
> 
>  RPReplay_Final1631250814.mov

![image](https://user-images.githubusercontent.com/15685376/132833832-3b080049-98d7-4ff4-976f-82b0886947e7.png)

Adjusted to Unicode on mac, just tried it, it did not meet expectations
Is there any progress in this area?

Eventually the xrdp server will support Chinese Unicode keyboard events?

Thank you!

https://user-images.githubusercontent.com/15685376/132838112-d4c1b67b-7ed4-4ec1-a601-4c1965e96421.mov

**Comment by zsj1029** [comment]
Run these commands to generate the keyboard mapping for your chosen input.
00000804 is chinese keyboard Mapping Code
xrdp-genkeymap km-00000804.ini
To copy it in the xrdp folder

sudo mv km-00000804.ini /etc/xrdp
Remember that you must change the permissions of the file, so that it can be used

sudo chown root:root /etc/xrdp/km-00000804.ini
Restart the service and it should work

sudo service xrdp restart

That'all . Enjoy it

**Comment by zsj1029** [comment]
Maybe Xrdp could set km-00000804.ini as default installation

**Comment by MagicStarTrace** [comment]
> Maybe Xrdp could set km-00000804.ini as default installation
Ok, thanks a lot!

Where can I get this (km-00000804.ini)?

Do I need to make special settings on the client side?

Thank You!

**Comment by zsj1029** [comment]
> Run these commands to generate the keyboard mapping for your chosen input. 00000804 is chinese keyboard Mapping Code xrdp-genkeymap km-00000804.ini To copy it in the xrdp folder
> 
> sudo mv km-00000804.ini /etc/xrdp Remember that you must change the permissions of the file, so that it can be used
> 
> sudo chown root:root /etc/xrdp/km-00000804.ini Restart the service and it should work
> 
> sudo service xrdp restart
> 
> That'all . Enjoy it

Just run command upon
Client no need make special settings
Change to chinese input method, it works

**Comment by seflerZ** [comment]
> > Run these commands to generate the keyboard mapping for your chosen input. 00000804 is chinese keyboard Mapping Code xrdp-genkeymap km-00000804.ini To copy it in the xrdp folder
> > sudo mv km-00000804.ini /etc/xrdp Remember that you must change the permissions of the file, so that it can be used
> > sudo chown root:root /etc/xrdp/km-00000804.ini Restart the service and it should work
> > sudo service xrdp restart
> > That'all . Enjoy it
> 
> Just run command upon Client no need make special settings Change to chinese input method, it works

Tried but doesn't work. @zsj1029 Did I miss something?

**Comment by zsj1029** [comment]
> > > Run these commands to generate the keyboard mapping for your chosen input. 00000804 is chinese keyboard Mapping Code xrdp-genkeymap km-00000804.ini To copy it in the xrdp folder
> > > sudo mv km-00000804.ini /etc/xrdp Remember that you must change the permissions of the file, so that it can be used
> > > sudo chown root:root /etc/xrdp/km-00000804.ini Restart the service and it should work
> > > sudo service xrdp restart
> > > That'all . Enjoy it
> > 
> > 
> > Just run command upon Client no need make special settings Change to chinese input method, it works
> 
> Tried but doesn't work. @zsj1029 Did I miss something?

make sure u have installed Chinese input method Fcitx in your OS first

**Comment by seflerZ** [comment]
@zsj1029 Here is the log. As you can see all keyboard maps has been found. I'm using Fcitx to use WuBi-86 input method too.
![image](https://github.com/neutrinolabs/xrdp/assets/2093588/f68662fe-6db3-46f6-9bd1-ec0e978017de)

Would you mind to provide the logs you have successfully enabled?

**Comment by MagicStarTrace** [comment]
> > Run these commands to generate the keyboard mapping for your chosen input. 00000804 is chinese keyboard Mapping Code xrdp-genkeymap km-00000804.ini To copy it in the xrdp folder
> > sudo mv km-00000804.ini /etc/xrdp Remember that you must change the permissions of the file, so that it can be used
> > sudo chown root:root /etc/xrdp/km-00000804.ini Restart the service and it should work
> > sudo service xrdp restart
> > That'all . Enjoy it
> 
> Just run command upon Client no need make special settings Change to chinese input method, it works

root@S0-GPU:/etc/xrdp#xrdp-genkeymap km-00000804.ini
xrdp-genkeymap:  unable to open display ''

How should this be resolved?

**Comment by seflerZ** [comment]
Well, I digged into the code recently. You can't send unicode to remote directly at present because xrdp simply doesn't support it. It does accept unicode input at method "xrdp_wm_key_unicode()" in file "xrdp_wm.c". But it converts it into scan code by comparing the glyphs and invokes "xrdp_wm_key()".

The reason xrdp module send scan code is because in the backend xorgxrdp, it simulated a virtual keyboard and uses "xf86PostKeyboardEvent()" to send keys. This function supports scan codes only.

I think what @zsj1029 said it can support other keyboard layouts other than en-US. For example, you can type in Greece glyphs or Japanese hiragana with unicode input enabled. It might work because it can be mapped to keys on the board. But you can not input other unicode which is not mapped to keys. For example, the Chinese has more than 10k characters, it's impossible to map them to the keyboard directly. Therfore, a way must be found to support input unicode directly, other than simulating keypresses.

As what I said, the "xf86PostKeyboardEvent()" supports scan code only. I don't know which X Window API supports it so I can upgrade the xorgxrdp input driver. @metalefty do you have any idea?

**Comment by matt335672** [comment]
I'm not as familiar with X11 internals as some of the other developers here, but I suspect the keycode model is too deeply embedded in X11 to implement this, at least with X11 backends.

The RFB protocol used by the VNC back end is documented here:-

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst

There's no provision for providing generic Unicode input as keypresses.

X11 key events (which are  visible to the application) are here. They are keycode dependent:-

https://tronche.com/gui/x/xlib/events/keyboard-pointer/keyboard-pointer.html

Despite the 'unsigned int' in the above, on the wire, X11 keycodes are only 8 bits, which gives us very limited possibilities:-

https://x.org/releases/X11R7.7/doc/xproto/x11protocol.html

I'll be very happy to be proved wrong here though, if anyone has better info than I have.

**Comment by seflerZ** [comment]
@matt335672 Okay, thank you. It seems X Server API takes over of hardware abstration only. We can make another way, to take advantage of iBus or Fcitx input method APIs to generate characters. It is centain that we can implement our iBus or Fcitx engine and accepts requests from xorgxrdp to input unicode characters through IPC calls. But this approch is difficult, costly and hard to maintain. I hope there is a way to send requests to iBus directly to generate unicode characters. I'm working on it.

**Comment by matt335672** [comment]
That sounds doable, @seflerZ but I agree with all of "difficult, costly and hard to maintain".

At the moment, the RDP input PDUs are send directly from xrdp to `xorgxrdp` or `VNC`. It might be possible to send the Unicode PDUs to `chansrv` instead and get that to interface to the session iBus. That's fine providing `chansrv` is connected to `xrdp`. There are still a few bugs in this area as I'm sure you are aware.

**Comment by seflerZ** [comment]
Hi, @matt335672 . I found it's much easier than I expected. We can implement a tiny iBus input engine within 100 code lines and use these functions to send unicode characters to iBus.

```
// Unicode identifier for Chinese character "你"
gunichar chr = 20320;
ibus_engine_commit_text(engine, ibus_text_new_from_unichar(chr));
```

As for the engine, we can use "ibus_engine_desc_new()" and "ibus_component_add_engine()" APIs to create a temporary one. 

So the question becomes, where shall we put this implementation, in "xrdp" or "xorgxrdp" module? I think in "xrdp" is more approachable, since "xorgxrdp" is designed for dealing with X Window system.

**Comment by matt335672** [comment]
It really depends on how the IPC works for ibus.

ibus runs on top of glib2, so it probably uses D-Bus, although I'm not sure about this.

Neither xrdp or xorgxrdp have a connection to the session D-Bus. I think you'll need to get the data into `xrdp-chansrv` which has full access to the session.

That's going to be quite fiddly. By all means have a go, but if you'd like a hand let me know what branch of xrdp you're working on.

**Comment by jsorg71** [comment]
I think @matt335672 is right, if you want to talk to ibus, chansrv is the place to do it.  There is already some non channel message in chansrv.  I think the rail code can send RDP orders for new window or update window for example.

I don't think ibus is good for general input.  I'll suggest another possibility.  If we can map unicode to keysyms we could do something like xdotool.  It looks if the keysym is in the current map, if it is, it uses it, if not, it looks for the first free scancode and maps the new keysym to the scancode, uses it, then removes it.
You can use xev and xdotool to see how it works.
We could do this in xorgxrdp where we already have a communication path.

**Comment by seflerZ** [comment]
I agree that iBus is not a general input solution. But if we implement our own input system, we'll need to deal with various window frameworks like Qt\Gtk2.0-4.0\x11\Wayland etcetera. That will be a big project...

As for "keysyms", It does map unicode characters to keys on the keyboard. But as I memtioned, some language like Chinese has more than 10k characters (Japanese also use characters origin from Chinese), we must simulate a gaint keyboard with thousands of keys to hold all the unicode characters. It is doable but some what weird though. (Besides, xrdp limited the size of keys to 256 at present.)

Of course, it will be great if we can find any simple and elegant approach.

**Comment by akallabeth** [comment]
would be really great to have this implemented, modern clients more and more start to use this as they do not have a keyboard to forward but some touch interface. (using `UnicodeKeyboard` is a huge help there as the guessing game `which keyboard layout is active` can be avoided)

**Comment by matt335672** [comment]
I can't see a simple and elegant approach myself I'm afraid:-
1) ibus isn't by any means globally used.
2) The reconnection to chansrv is quite flaky at times for current xrdp versions. We'd have to solve this for a robust solution based on chansrv.
3) Jay's method is (I think) going to generate a lot of `MappingNotify` events for all X applications. We also can't use it for the few remaining use-cases where a VNC backend is necessary.

If we did implement something in `chansrv`, a production solution would need a way for the user to configure the desktop input method - a global method wouldn't be adequate.

At the same time, if @seflerZ want to try modifying chansrv for prototyping purposes I'm happy to give him a hand. We'll learn more that way about whether a robust solution can be found.

**Comment by seflerZ** [comment]
@matt335672 Thank you so much. If I have troubles, may I contact you though something like IM or email？

I'm digging into the chansrv codes now. I managed to figure out the call chain from "xrdp" to "chansrv". Now I know they communicate with each other by using the UNIX domain socket. The method "server_send_to_channel()" seems to be the best choice if we need to send unicode input PDU from xrdp to chansrv. But it tells it's a bad call if "chansrv" or "sesman" is in use.

```
int
server_send_to_channel(struct xrdp_mod *mod, int channel_id,
                       char *data, int data_len,
                       int total_data_len, int flags)
{
    struct xrdp_wm *wm;

    wm = (struct xrdp_wm *)(mod->wm);

    if (wm->mm->use_chansrv)
    {
        /* Modules should not be calling this if chansrv is running -
         * they can use server_chansrv_in_use() to avoid doing this */
        LOG_DEVEL(LOG_LEVEL_ERROR,
                  "Bad call of server_send_to_channel() detected");
        return 1;
    }

    return libxrdp_send_to_channel(wm->session, channel_id, data, data_len,
                                   total_data_len, flags);
}
```
I'm wonding if there is any reasons for doing this?

**Comment by matt335672** [comment]
@seflerZ 

I had a think about this over the weekend, and had a look at the code myself. It's pretty hard to find your way around it, so I thought I'd put something together quickly to get you started. That way you can focus on the immediate problem rather than worrying about how xrdp is put together.

I've implemented a basic method to send unicode input from xrdp to chansrv. Code is here, based on the devel stream:-

https://github.com/matt335672/xrdp/tree/initial_ibus_testing

This code adds an `--enable-ibus` switch to configure. If this is specified, Unicode keyboard events are passed to chansrv (if it's up) and simply logged in chansrv in `process_message_unicode_key_press()`.

I've added the relevant libraries to chansrv, so you should be able to expand the code in there and call ibus methods.

This is pretty basic and would need more work before it went into production. After you've played with it, we can make it more robust if you think between us we can make something useful.

Also, being based in the UK, I can't find a way to test this here. If you have any suggestions, please let me know.

**Comment by Kishi85** [comment]
> Also, being based in the UK, I can't find a way to test this here. If you have any suggestions, please let me know.

Testing should be easily done by using a phone/tablet and trying to send emojis from the on-screen keyboard as they are sent as Unicode characters via Microsofts Android RDP client

**Comment by akallabeth** [comment]
> > Also, being based in the UK, I can't find a way to test this here. If you have any suggestions, please let me know.
> 
> Testing should be easily done by using a phone/tablet and trying to send emojis from the on-screen keyboard as they are sent as Unicode characters via Microsofts Android RDP client

`xfreerdp3`  supports reading symbols from a pipe (check the command line help)
that way you can just echo `utf-8 encoded` stuff to a pipe and it is sent as `ucs-2` encoded data.

**Comment by matt335672** [comment]
Thanks both - that's very useful indeed.

@akallabeth - I spent a bit of time looking about in `freerdp3` yesterday and completely missed the pipe option! For the record, I'm now using a command line like the following :-

```
xfreerdp /gfx /kbd:pipe:/tmp/input.pipe /v:<hostname> /size:1280x1024 /u:testuser /d: /p:<password>
```

I can then push stuff through xrdp as expected:-

```
echo -n '😉' >/tmp/input.pipe
```
@seflerZ - I've fixed a significant bug in the code I pushed. Also, I've remapped surrogate pairs as well, so I can send smileys in. I'm getting log messages like the following in chansrv:-

```
2024-03-26T10:12:41.980+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x00000073 received down=1
[2024-03-26T10:12:41.175+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x00000073 received down=0
[2024-03-26T10:12:43.443+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x0000006c received down=1
[2024-03-26T10:12:43.613+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x0000006c received down=0
[2024-03-26T10:12:43.638+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x0000006c received down=1
[2024-03-26T10:12:43.715+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x0000006c received down=0
[2024-03-26T10:12:43.917+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x00000073 received down=1
[2024-03-26T10:12:43.966+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x00000073 received down=0
[2024-03-26T10:12:44.719+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x00000073 received down=1
[2024-03-26T10:12:44.139+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x00000073 received down=0
[2024-03-26T10:12:58.887+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x0001f602 received down=1
[2024-03-26T10:12:59.106+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x0001f602 received down=0
[2024-03-26T10:13:36.665+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x0001f609 received down=1
[2024-03-26T10:13:36.737+0000] [INFO ] [process_message_unicode_key_press(chansrv.c:844)] Unicode char 0x0001f609 received down=0
```

**Comment by seflerZ** [comment]
@matt335672 Thanks. I'm dealing with the iBus now. Got some progresses but also problems. But I think it won't take too much long.

**Comment by seflerZ** [comment]
Hello! Good news. It is basically working now!

https://github.com/neutrinolabs/xrdp/assets/2093588/629f5ac7-b14c-4334-808c-5cb312210f5b

**Comment by matt335672** [comment]
That's great @seflerZ 

When you've had a bit more time to make sure you're happy with it feel free to raise a PR on my repo. I'll have a look and get my stuff better engineered and then we can put it out for wider review.

**Comment by seflerZ** [comment]
@matt335672 Hi, this feature is almost done. However according to MS-RDPBCGR 2.2.7.1.6 Input Capability Set, there is a flag sent from client named TS_INPUT_CAPABILITYSET to indicate it supports unicode input service. I want to use it as a flag to decide whether the iBus component to be initialized (otherwise resource wasted). 

I managed to figured out I can add a new attribute named "support_unicode_input" the "struct xrdp_client_info" and set it in "xrdp_caps_process_input" method of "xrdp_caps.c". However when I add the attribute the xorgxrdp seems stopped working and go into black screen.

I know the "struct xrdp_client_info" is shared by "xrdp" and "xorgxrdp", but I don't know why it can not be added easily. This may be caused by the "xrdp_client_info" structure is transferred through socks to "xorgxrdp". Would you help me to figure it out? Or we can just do the initialization no matter what the client requests. It works though.

**Comment by metalefty** [comment]
@seflerZ  Did you rebuild xorgxrdp after you added a new attribute to xrdp_client_info with new xrdp_client_info.h?  Usually, shared structures contain padding but we didn't add padding so I guess even the simple adding of new attributes may cause a glitch.

**Comment by matt335672** [comment]
@seflerZ - I had some thoughts on this.

I'm really short of time this week, but I saw the workflow going like this:-

1) chansrv is built with ibus/fcitx/whatever
2) chansrv sends a subscription message to xrdp when it starts to say it can handle Unicode injection
3) At that point xrdp can check the flags it was sent, and either forward Unicode to chansrv,, or not.

That puts the decision as to whether Unicode is supported into chansrv, rather than making it a bit of a mix between chansrv and xrdp.

The client info structure is another way to do it of course.

I'll happily add more detail when I can. In the meantime, feel free to come back to me about this.

**Comment by seflerZ** [comment]
Yeah, there is not need to transfer the flag to xorgrdp module. I was intend to use the flag to decide whether the iBus will be initialized. Any way, I'll prepare the PR to make my question more clear.

**Comment by akallabeth** [comment]
@matt335672 @seflerZ  that might not be sufficient. RDP input capability set is sent by server to client and client to server.
so, if the server announces support the client decides if it will use it or not. (I might have missed when `chanserv` starts up, so please ignore if that happens before the session initialization)

**Comment by matt335672** [comment]
Thanks @akallabeth 

At the moment the server always announces Unicode support to the client. If the client then sends Unicode, there's a fallback implementation that reverse-looks up the character in the existing character map. If the character is found, the relevant keypress event is generated. We need this for the login screen, as Unicode support is negotiated before the session is started.

`chansrv` is started as part of the user's session, so it's relatively late in the process.

@seflerZ's function is replacing this fallback in the event that chansrv decides it can provide the Unicode character injection directly.

**Comment by seflerZ** [comment]
@matt335672 @metalefty I'm ready to raise the PR, but when I switched to the latest devel branch I can not start xrdp. The connection established normally but my screen resulted in black. Even if I compile the devel branch with fresh Ubuntu installation I can't get xrdp function normally. Did I miss something?

**Comment by seflerZ** [comment]
Hello, everyone. The feature is ready. This is the [branch](https://github.com/neutrinolabs/xrdp/compare/devel...seflerZ:xrdp:unicode_contr) I will raise for PR. I've tested it for two weeks and it works perfectly. For testing, just compile the "xrdp" with "./configure --enable-ibus --enable-fuse" (You need have iBus and lastest xorgxrdp devel branch installed). One of the best benefits of supporting unicode input is, you can use your phone's voice input to input long text by one time. It's just awesome (especially in small screen devices, lol)! Thanks for @matt335672 's help!


https://github.com/neutrinolabs/xrdp/assets/2093588/174b37eb-41a0-45d2-954a-5feab7fd7e8f



Besides, I still have two questions left:
1. Is located in "xrdp_mm.c:3043". Where this the best place to trigger iBus component initialization? Currently I put in the "xrdp_mm_chansrv_connect".
2. Is located in "input_ibus.c:226". The iBus feature needs to connect to iBus as we know, but the iBus daemon may not be ready when the user first logged in. So here I just make process waiting for 3 seconds. I don't think it's an elegant way, but I can find a flag which indicate iBus daemon is ready at present.

**Comment by matt335672** [comment]
Hi @seflerZ 

In answer to your questions:-
1. That seems like a good idea. Following on from that, it might be useful (if the initialization succeeds) for chansrv to send a message to xrdp saying that it supports Unicode input. That way, if anything goes wrong, xrdp won't send Unicode to chansrv and might be able to do something else with it. I can give you a hand to make that change if you like.
2. What happens if the daemon isn't ready? Can you pick that up, sleep for a small amount (say 500ms) and then try again with a loop count? It's not elegant either, but is more adaptive.

**Comment by seflerZ** [comment]
@matt335672 
1. Yes, I was intend to add an attribute in client_info to indicate unicode input is supported and set it in method "xrdp_caps_process_input" in file xrdp_caps.c but resulted in black screen. It seems that the  xorgaxrdp has compatibility issues (I'm sure I've recomipled it with latest client_info struct because I know it is shared with "xorgxrdp" module). Your help is highly appreciated.
2. If the iBus daemon is not ready, then the ibus_init() method will fail and fall back to non-unicode support input. It still work, but you know it a little bit weired since users've been satisfied with everything needs to enable unicode input.

**Comment by matt335672** [comment]
I'll take 2) first:-

> If the iBus daemon is not ready, then the ibus_init() method will fail and fall back to non-unicode support input. It still work, but you know it a little bit weired since users've been satisfied with everything needs to enable unicode input.

Is it possible to detect this and retry?

> Yes, I was intend to add an attribute in client_info to indicate unicode input is supported and set it in method "xrdp_caps_process_input" in file xrdp_caps.c but resulted in black screen. It seems that the xorgaxrdp has compatibility issues (I'm sure I've recomipled it with latest client_info struct because I know it is shared with "xorgxrdp" module). Your help is highly appreciated.

I think we need an additional message from chansrv to xrdp to say Unicode input (via ibus/fcitx5/whatever) is supported. When that message is received, xrdp will send any Unicode characters to chansrv.

Data flow goes as follows. The first three steps are part of the current v0.9.x implementation
1) Chansrv is started
2) Chansrv receives 'channel setup' message from xrdp
3) Chansrv sets up channels
-------------------------------
4) Chansrv starts one or more input methods (currently ibus only)
5) If an input method is started successfully, chansrv sends a message to xrdp saying that Unicode input is possible
6) xrdp sends Unicode to chansrv (if it's received the message, and chansrv is still up).

We don't really need to check the client flag for Unicode support. We always set the 'Unicode supported' flag in our initial attributes. We either get Unicode from the client or we don't.

What do you think?

**Comment by seflerZ** [comment]
Well, for the first part. I tried to use a loop to retry if ibus_init() resulted not connected but it's very strange that once it returns error no matter how many times you've tried the result won't change, it's not connected.
For the second, the question is how xrdp could know ibus/fcitx is running in the host. Should xrdp module use its priviledges to read process running on the host? If that is possible, I can try to implement it.

**Comment by matt335672** [comment]
The second part looks like this:-

1) Chansrv calls ibus_init()
   a) If that call works, chansrv tells xrdp to forward Unicode characters
   b) If the call doesn't work, chansrv does nothing. xrdp does not forward Unicode characters.

So xrdp doesn't need to know anything other than whether chansrv has asked for Unicode or not.

Does that make sense?

**Comment by seflerZ** [comment]
Sorry. I made the wrong order. I'm talking about Q1. That is whether we should have a flag to init ibus input or not. Otherwise the ibus thread will be wasted. Of course, we can always consider the client support unicode input and do fall back if not. In that case, we do not need that flag and Q1 can be resolved.The Q2 is about how to remove the sleep which is necessary now. Because even ibus was installed and properly configured, if we do no sleep when the session is firstly connected, the ibus could not be connected. So if we do fall back here, it does not work as it is expected.

**Comment by matt335672** [comment]
OK - I see now. If the client doesn't support ibus, we create a thread we don't use. I agree we should try not do do that.

I'm a bit short of time right now, but I'll get a patch to you ASAP.

**Comment by matt335672** [comment]
@seflerZ (and anyone else reading) - I've added [PR #2](https://github.com/seflerZ/xrdp/pull/2) to your repository

Happy to discuss.

**Comment by poetic-edge** [comment]
Thank you for your contributions. You have provided me with great help.ヾ(≧▽≦*)o

 However, I have also discovered two bugs. 
1. When I specify to launch a certain program, such as a browser, IBus doesn't work. Currently, I manually start IBus in that session to resolve the issue. 
2. In my client, resizing the window repeatedly triggers the function **xrdp_caps_process_input**. The original UIS_ACTIVE state is reset to UIS_SUPPORTED, which prevents subsequent Unicode delivery.

**Comment by seflerZ** [comment]
Hi. Not quite sure what do you mean by start a new program but iBus doesn't work. iBus should start with the user session. @poetic-edge

**Comment by poetic-edge** [comment]
@seflerZ  In a similar way to "rdesktop -s: shell / seamless application to start remotely," you can achieve the desired functionality.

**Comment by matt335672** [comment]
@poetic-edge - are you saying that running without a full desktop session is the problem?

**Comment by poetic-edge** [comment]
> @poetic-edge - are you saying that running without a full desktop session is the problem?

Yes, in this case, ibus will fail.

**Comment by seflerZ** [comment]
I think it is kind of like Remote APP.

**Comment by matt335672** [comment]
This might be something we need to fix outside the scope of this PR.

When a modern desktop is started on Linux, there's a whole load of `systemd --user` services that get started too. One of these is the input method daemon. Starting individual applications will need some, but possibly not all of these services.

@seflerZ - sorry to introduce more delay to this, but I'll be away from my dev. environment for a week or so. When I get back (assuming no emergencies) I want to get this merged into `devel`.

**Comment by JulyIghor** [comment]
> @poetic-edge - are you saying that running without a full desktop session is the problem?

I use this bash code, it fixes the issue without full desktop environment. I see no reason for the sleep to be in the c++ code.

```
IBUS_ADDRESS=""
while [ "$IBUS_ADDRESS" = "" ] || [ "$IBUS_ADDRESS" = "(null)" ]; do
    sleep 1
    IBUS_ADDRESS=$(ibus address)
done
export IBUS_ADDRESS
```
