### ISSUE TITLE
clipboard file: Odd behaviour when transferring files client to server direction

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#1992]
## Overview

Odd behaviour when transferring files client to server direction.

I haven't figure out what is the issue but it appears the odd behaviour occurs if the filename contains non-ASCII characters.

See the attached movies for details.

## Server: Alma Linux 8 / xrdp 0.9.16

Desktop environment: Xfce 4.14

```
# cat /etc/os-release
AlmaLinux release 8.4 (Electric Cheetah)
```

```
$ rpm -qa |grep xrdp
xorgxrdp-0.2.16-3.el8.x86_64
xrdp-0.9.16-2.el8.x86_64
xrdp-selinux-0.9.16-2.el8.x86_64
```

```
xrdp 0.9.16
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      --with-socketdir=/run/xrdp
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 1.1.1g FIPS  21 Apr 2020
```

## Client: macOS Remote Desktop Version 10.6.8
![スクリーンショット 2021-09-08 15 54 52](https://user-images.githubusercontent.com/941609/132461017-083d6f20-6d3b-4168-a96d-4ad6a330d5f8.png)

## Movie of reproduction

https://user-images.githubusercontent.com/941609/132464409-352dba21-896b-4a28-a973-2020435ab5d9.mov

### Only the first one file is transferred 

https://user-images.githubusercontent.com/941609/132469218-34c7636b-54c7-49b6-b1e2-273b40e17f7a.mov

**Comment by matt335672** [comment]
Interesting.

Can you create a tar.gz archive of three smaller files with the same names and attach it to the issue (I think that should work)? We can then look at how xrdp processes the names.

**Comment by metalefty** [comment]
Here it is.

[files.zip](https://github.com/neutrinolabs/xrdp/files/7132609/files.zip)

**Comment by matt335672** [comment]
I get something very similar when I do the paste. In the target directory:-

```
-rw------- 1 xtestuser xtestuser      0 Sep  9 11:17 ࡊ汙ꕝǗ
-rw------- 1 xtestuser xtestuser 494381 Sep  9 11:17 ファイル1.png
```

**Comment by matt335672** [comment]
Found it.

The code to parse a [CLIPRDR_FILEDESCRIPTOR](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/a765d784-2b39-4b88-9faa-88f8666f9c35) works OK for ASCII filenames, but gets the length too short for more complex filenames. As a result, when more than one CLIPRDR_FILEDESCRIPTOR is sent in a [CLIPRDR_FILELIST](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/3570c2e4-cdd7-4460-8a7e-1a4595f5ebdc), only the first file descriptor is read correctly.

The problem is here:-

https://github.com/neutrinolabs/xrdp/blob/3e5948f52ea6930439715e258817d7c5e7c37dde/sesman/chansrv/clipboard_file.c#L579-L583

The return result of an `wcstombs()` call is used to work out the number of character to skip in the buffer. This is only going to produce the right result for simple filenames. It's simpler to use the return result of `clipboard_in_unicode()` to do this directly.

I've got some other minor code improvements in this area as well. PR to follow.
