### ISSUE TITLE
XRDP failure with Firefox

### ISSUE THREAD

**Issue by ygoe** [neutrinolabs/xrdp#200]
I just noticed a strange rendering bug with Firefox, only on a single website. Other sites rendered fine. Firefox was just installed, with no extensions.

Environment:
Ubuntu 14.04 amd64, XFCE desktop, Firefox 34, XRDP devel branch

Steps to reproduce:
- Install packages: xfce4 xfwm4-themes xfce4-terminal geany firefox firefox-locale-de
- Start Firefox
- Open URL: http://dev.unclassified.de/de

Actual result:
Page rendered as a complete mess of fragments of anything. Also, after a while, the desktop becomes unresponsive. Further RDP connection retries fail after login (black screen). Restarting the xrdp service and killing all Firefox processes lets me login and start Firefox again, but with the same result.

Excepted result:
Well, correct rendering, no crash.

The log contains no error message other than that appearently there are constant connection tries from everywhere in the world.

**Comment by ShahimEssaid** [comment]
I'm also having issues with Firefox. I've installed X11rdp-o-matic on Ubuntu 14.04 and I connect with Windows 7 Remote Desktop.  When I use Firefox the remote session freezes (as soon as few minutes) and there is no way to recover from this. I have to kill -9 the x11rdp process to end the session. I've switched to Chromium since I saw this bug and the problem went away.

I noticed that X1rdp-o-matic does apply a the openGL patch mentioned above as seen here:
https://github.com/scarygliders/X11RDP-o-Matic/blob/master/rdp_Makefile.patch

I'll try to do some more debugging when I have a chance but my problem was clearly caused by Firefox.

**Comment by scarygliders** [comment]
@ShahimEssaid 

Does Firefox on that system have "Always use hardware acceleration" enabled? If so, you could try disabling hardware acceleration and see if that improves stability.

**Comment by ShahimEssaid** [comment]
@scarygliders 
Thanks for the tip. So far (few hours) no Firefox problems with this option turned off.

**Comment by moobyfr** [comment]
With today's version of Xrdp X11rdp or Xorg module, there is no more problem displaying these pages.

**Comment by metalefty** [comment]
moobyfr reported there is no more problem now.
