### ISSUE TITLE
specify/reconnect  existing xorgxrdp session

### ISSUE THREAD

**Issue by pow248** [neutrinolabs/xrdp#2007]
Feature/Issue
Ability to specify by session ID, xorg display etc on the login page, by RDP client info or other means.
Perhaps this is similar or alternate to #561, without security or second page/window creation interface issues?
I haven't been able to find a way reconnect to an existing session with xorgxrdp with UBDC set?

Context:
I am running xrdp with xorgxrdp and session policy UBDC.
I wish to be able to specify which session to reconnect to.
Existing sources I have found discuss using port number to connect to existing session.
From a user's perspective specifying the X11 socket location, display or session ID as an argument could be additional arguments at the login window.
Workaround at this stage would appear to be a different user per session, which brings other issues.

Further discussion:
I'm guessing need to specify output /add additional arguments to session_get_bydata() ?
I am finding  xrdp_login_wnd.c challenging to modify on first read, if that is the path forward for user specifying the session? 

For example, can login beforehand and get session id per attached command line output.
[example-xrdp-sesadmin-out.txt](https://github.com/neutrinolabs/xrdp/files/7274358/example-xrdp-sesadmin-out.txt)

Could also note X11 display before disconnection, looking at log output etc, running processes, temp directory etc.

**Comment by matt335672** [comment]
Hi @pow248.

If you set the 'C' in 'UDBC', you will need to connect from the same client TCP port to reconnect to your session. I doubt this is happening. It doesn't seem like a particularly useful feature to me, but maybe I'm missing a use-case.

There's also the complication of `systemd --user`. If you're running on a modern Linux distribution with systemd enabled, you can't easily have more than one session per user. The reason is that on first login the user gets an instance of `systemd --user` running for shared long-term services running for that user. This process has a DISPLAY variable which needs to be set to the currently active DISPLAY for the user. This can be the console, a VNC session or an xrdp session, but importantly only one of these is supported at a time.

This is a limitation of the way systemd is implemented currently.

You don't say what system you're running on, so I can't say whether this is likely to affect you or not.

**Comment by matt335672** [comment]
I'm closing this - now more input from OP and the main issues seem to be covered in #561
