### ISSUE TITLE
does xrdp support copy/paste directory at all?

### ISSUE THREAD

**Issue by monkey-jsun** [neutrinolabs/xrdp#2029]
I just tried and it failed, while other copy/paste works (for text and files).

I debugged and saw some errors like following, which seem to suggest directory copy/paste is not supported.  Can anyone confirm that?

sesman/chansrv/clipboard_file.c, http://chipitsine.github.io/xrdp/report-4a9cd0.html

Sending:
[2753235096]: CLIPFILE   clipboard_c2s_in_files: 664 : ERROR: clipboard_c2s_in_files: skipping directory not supported [certs]

fetching:
[2753884612]: CLIPFILE   clipboard_get_file: 212 : ERROR: clipboard_get_file: file [/home/jsun/Desktop/test1/test2] is a directory, not supported

**Comment by metalefty** [comment]
What do you mean by asking that? 

If you simply asking: 
Does xrdp support directory copy&paste? -- No, at all. That's why the log is recorded. We xrdp developers decided to record such log because it is not supported.

Can xrdp support directory copy&paste? -- It is actually supported in Windows to Windows RDP, so xrdp can support it in theory but not supported at the moment.

**Comment by matt335672** [comment]
No more feedback - closing.
