### ISSUE TITLE
xrdp Showing Black Screen, Even for Wrong Log-in info Prompts

### ISSUE THREAD

**Issue by RyleeGM** [neutrinolabs/xrdp#2035]
xrdp is running on an Ubuntu 20.04 system. I have tried many of the recommendations in other issue threads to no avail.

I am attempting to log in using the Windows Remote Desktop client on mac but issue is also present when trying to use Remmina on another Ubuntu Linux box.

I get a black screen when attempting to connect. When entering bad credentials the window resizes to the size of the error box but the display remains black.

xrdp was working perfectly a short time ago and has stopped for an unknown reason.

Here are some of the log files:
[xorgxrdp.10.log](https://github.com/neutrinolabs/xrdp/files/7428490/xorgxrdp.10.log)
[xrdp.log](https://github.com/neutrinolabs/xrdp/files/7428491/xrdp.log)
[xrdp-sesman.log](https://github.com/neutrinolabs/xrdp/files/7428492/xrdp-sesman.log)

**Comment by matt335672** [comment]
You're going to have problems with the version of XRDP you have and the NVidia driver. Because you have these drivers installed, the Xorg server wants to use the hardware console and it does not have privilege to do so.

We have a couple of developers looking at NVidia co-existence, but its not there yet, and it's certainly not available for the packages provided for 20.04.

Can you try to use the Xvnc backend driver? That should work OK with the NVidia driver on 20.04.

**Comment by RyleeGM** [comment]
I attempted using the X.org display driver instead of the Nvidia proprietary driver and the system continues to exhibit the same behavior.

**Comment by matt335672** [comment]
If you look in the xorgxrdp.10.log file you may find that the system is still trying to load a physical driver.

Can you try to use the Xvnc backend driver? That should work OK with the NVidia driver on 20.04.

**Comment by matt335672** [comment]
No more info - closing
