### ISSUE TITLE
hide the version to network scanner

### ISSUE THREAD

**Issue by massimiliano-dalcero** [neutrinolabs/xrdp#2071]
Hi,
there is the possibility to hide or modify the "version name" expose on the network?

If I scan port 3389 with nmap and flag "-sV"  I see:

```
PORT     STATE SERVICE       VERSION
3389/tcp open  ms-wbt-server xrdp
```

there is a "trick" (also modifying the code) to replace "xrdp" with "other stuff" ?

Thanks and best regards :)

**Comment by metalefty** [comment]
The version name is not the string that xrdp advertise, it is guessed by nmap. So xrdp has nothing to hide.
It may be possible to trick the nmap. However, nmap will progress. It is a cat-and-mouse game.

The nmap probe table can be found at `nmap-service-probes` in nmap source code. These are fingerprints.
```
% grep ms-wbt-server nmap-service-probes
match ms-wbt-server m|^\x03\0\0\t\x02\xf0\x80!\x80| p/xrdp/ cpe:/a:jay_sorg:xrdp/
match ms-wbt-server m|^\x03\0\0\x13\x0e\xd0\0\0\x124\0\x02\x1f\x08\0\x02\0\0\0| p/Microsoft Terminal Services/ o/Windows/ cpe:/o:microsoft:windows/a
match ms-wbt-server m|^\x03\0\0\x0b\x06\xd0\0\0\x124\0$| p/Microsoft Terminal Services/ o/Windows XP/ cpe:/o:microsoft:windows_xp/a
# Remove 3388 and 3389 if the ssl/ms-wbt-server match below doesn't catch stuff well enough.
match ms-wbt-server m|^\x03\0\0\x0b\x06\xd0\0\0\x12.\0$|s p/Microsoft Terminal Service/ o/Windows/ cpe:/o:microsoft:windows/a
match ms-wbt-server m|^\x03\0\0\x17\x08\x02\0\0Z~\0\x0b\x05\x05@\x06\0\x08\x91J\0\x02X$| p/Microsoft Terminal Service/ i/Used with Netmeeting, Remote Desktop, Remote Assistance/ o/Windows/ cpe:/o:microsoft:windows/a
match ms-wbt-server m|^\x03\0\0\x11\x08\x02..}\x08\x03\0\0\xdf\x14\x01\x01$|s p/Microsoft NetMeeting Remote Desktop Service/ o/Windows/ cpe:/a:microsoft:netmeeting/ cpe:/o:microsoft:windows/a
match ms-wbt-server m|^\x03\0\0\x0b\x06\xd0\0\0\x03.\0$|s p/Microsoft NetMeeting Remote Desktop Service/ o/Windows/ cpe:/a:microsoft:netmeeting/ cpe:/o:microsoft:windows/a
match ms-wbt-server m|^\x03\0\0\x0b\x06\xd0\0\0\0\0\0| p/xrdp/ cpe:/a:jay_sorg:xrdp/
match ms-wbt-server m|^\x03\0\0\x0e\t\xd0\0\0\0[\x02\xa1]\0\xc0\x01\n$| p/IBM Sametime Meeting Services/ o/Windows/ cpe:/a:ibm:sametime/ cpe:/o:microsoft:windows/a
match ms-wbt-server m|^\x03\0\0\x0b\x06\xd0\0\x004\x12\0| p/VirtualBox VM Remote Desktop Service/ o/Windows/ cpe:/a:oracle:vm_virtualbox/ cpe:/o:microsoft:windows/a
```

**Comment by matt335672** [comment]
Indeed.

The tracing through `nmap-service-probes` can be seen by running `nmap -p3389 -sV --version-trace`. On my system that shows a match at this rule:-

```
# xrdp disconnects this way if you look at it funny.
match ms-wbt-server m|^\x03\0\0\t\x02\xf0\x80!\x80| p/xrdp/ cpe:/a:jay_sorg:xrdp/
```

So yes, we can change the code to miss this rule, or to hit one of the previous rules, for example the Windows 10 rule. If we do that though, we'll also need to implement the corresponding functionality!

Since we don't yet support NLA (and won't for some time), checking the Server X.224 Connection Confirm PDU will confirm that we're likely xrdp anyway, so it's relatively simple for the service probe table to be updated to cope with this.

I'm closing this for now, as the lack of NLA means we can't in practice do anything about this yet. We can maybe reconsider it when NLA is supported.

**Comment by massimiliano-dalcero** [comment]
thanks for your kindly response :)
