### ISSUE TITLE
xrdp_wm_drdynvc_up

### ISSUE THREAD

**Issue by JSSSSSSSSSS** [neutrinolabs/xrdp#2097]
It seems that this function is not implemented.
![image](https://user-images.githubusercontent.com/58905687/147439319-2bb87670-4246-4e26-8538-95945065a21b.png)

**Comment by matt335672** [comment]
Thanks @JSSSSSSSSSS.

I've had a look into this.

The declaration in `xrdp/xrdp.h` was introduced in ae1514c1679e87edfdeba5ca3eb2b3659ef44b1a at the same time that the function `xrdp_mm_drdynvc_up()` was added. I can't find any definitions for  `xrdp_wm_drdynvc_up()` in the code at this time, or at any time since, so I think this is simply a typo.

**Comment by JSSSSSSSSSS** [comment]
fine
