### ISSUE TITLE
Extremely poor performance on Microsoft Android RDP Client

### ISSUE THREAD

**Issue by t123yh** [neutrinolabs/xrdp#2157]
Hi,

I installed xrdp v0.9.18 on Ubuntu. The performance is normal on desktop RDP clients (Windows, macOS), but if I connect from Android client (version 10.0.13.1174), it takes an extremely long time to load one frame (~5sec), makes it totally unusable. I am using LAN and 802.11ac WiFi, so network bandwidth is not an issue.

BTW, how to donate to xrdp? This project really helps me a lot.

**Comment by matt335672** [comment]
That sounds interesting.

It'll take me a while to get to this I'm afraid, as I'm focussed on something else for a couple of weeks. I've found the client on the Play store at least.

What version of Ubuntu are you using, and which desktop? Also, how have you installed 0.9.18? Can you give me the output of `xrdp -v`?

**Comment by t123yh** [comment]
@matt335672 I'm running up-to-date Ubuntu 20.04 with the default gnome desktop. I installed xrdp by building .deb package from the latest xrdp souece with [Ubuntu build files](http://archive.ubuntu.com/ubuntu/pool/universe/x/xrdp/xrdp_0.9.17-2ubuntu2.debian.tar.xz).

Here's the output of `xrdp -v`:

```
xrdp 0.9.18
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -fdebug-prefix-map=/home/lxb/xrdp-build/xrdp=. -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/home/lxb/xrdp-build/xrdp/pkgconfig

  Compiled with OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by matt335672** [comment]
Thanks - that's useful. Give me a bit of time and I'll get back to you.

**Comment by matt335672** [comment]
Well I've managed to take a look at this, and there seem to be some significant client issues to do with buffering.

Client I've got is a Xiaomi Mi A2 Lite running Android 10.

Rather than the GNOME desktop, I set up a simple session using an xterm and twm.

On the server side I monitored bandwidth with `iftop`:-

```
sudo iftop -f "tcp port 3389"
```

In the xterm I entered the relatively simple command `find / -ls` to generate a lot of text output.

The network interface peaked at around 2-4 Megabits per second. I expected a lot more than that frankly, on 802.11ac

The oddest thing however was that after the find command finished (which was visible from a `ps -ef` on an ssh session), the rdp session continued scrolling by for a few minutes! Ctrl-C was not effective. At that point, the network traffic dropped to zero, but the client carried on scrolling.

I tried a few other settings, but they made matters worse. Using the native screen resolution on my phone dropped the data rate to well under a megabit/sec. Turning off TLS helped a bit on my hardware, but the app was still unusable.

I don't know what to suggest - I can't see anything further we can do on our side. It might be worth measuring the bandwidth you're getting from your client, as you may find it's a lot lower than you're expecting.

**Comment by t123yh** [comment]
Hi Matt,

Thanks for your effort. The client is working very well on MSRDP server, so there must be differences.

> It might be worth measuring the bandwidth you're getting from your client, as you may find it's a lot lower than you're expecting.

By “bandwidth” you mean the maximum Wi-Fi bandwidth (which can be tested with http download) or the real consumed bandwidth when running RDP?

**Comment by matt335672** [comment]
RDP bandwidth. The iftop will measure what's happening to the TCP socket connection. This will depend on the behaviour of the application on both sides.

Just tried aRDP free for comparison. It works fine, both with my setup and with GNOME. This isn't a recommendation - just an observation.

**Comment by t123yh** [comment]
> Just tried aRDP free for comparison. It works fine, both with my setup and with GNOME. This isn't a recommendation - just an observation.

aRDP works for me.
