### ISSUE TITLE
Error building xrdp under macOS Monterey

### ISSUE THREAD

**Issue by d3adwolf** [neutrinolabs/xrdp#2159]
The error is related to #2160 
---
Built using the instructions from the [Wiki](https://github.com/neutrinolabs/xrdp/wiki/Building-on-OSX-%28not-official%29) of this repository:
```css
dmitrii@macbook-pro-dmitrii ~/D/xrdp-0.9.18.1> make

/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in common
make[2]: Nothing to be done for `all'.
Making all in vnc
make[2]: Nothing to be done for `all'.
Making all in xup
make[2]: Nothing to be done for `all'.
Making all in mc
make[2]: Nothing to be done for `all'.
Making all in libxrdp
make[2]: Nothing to be done for `all'.
Making all in libpainter
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
make[4]: Nothing to be done for `all'.
Making all in include
make[4]: Nothing to be done for `all'.
Making all in pkgconfig
make[4]: Nothing to be done for `all'.
Making all in librfxcodec
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in include
make[4]: Nothing to be done for `all'.
Making all in src
make[5]: Nothing to be done for `all-am'.
Making all in tests
make[4]: Nothing to be done for `all'.
Making all in sesman
Making all in libscp
make[3]: Nothing to be done for `all'.
Making all in tools
make[3]: Nothing to be done for `all'.
Making all in chansrv
make[3]: Nothing to be done for `all'.
  CC       sesman.o

error: unable to open output file 'sesman.o': 'Operation not permitted'
1 error generated.
make[3]: *** [sesman.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
---
### Build versions:
**macOS Monterey `v12.2.1`
xrdp `v0.9.18.1`
xorgxrdp `v0.2.18`**

**Comment by matt335672** [comment]
```
error: unable to open output file 'sesman.o': 'Operation not permitted'
```

I can't find any Mac Monterey man pages online, but this looks as simple as the `open()` system call makde by the compiler returning `EPERM`. Have a look at your man pages and see if you can get any insight there. Check the file permissions and ownership of `sesman.o` and the enclosing directory for a start.

None of the xrdp team have access to a Mac. I'll leave this open for a couple of weeks in case someone else is able to respond, then I'll close it.

**Comment by matt335672** [comment]
Just as a footnote, if you've been running `sudo make` (like you are in #2160) you'll have files owned by `root` in your build directory. That will probably cause this.

**Comment by paulb39** [comment]
Matt, I am trying to compile this on Monterey as well.
I know osx is not support but the wiki does say to do sudo make install  
I have not tried doing it as sudo because of this post. But I am trying to understand. The wiki says to do sudo make install - are you saying that is incorrect and we should be be able to compile with just make install?
With make install I get mkdir: /etc/xrdp: Permission denied, which makes me feel like we need sudo
I had other mkdir errors until I added --prefix=/Users/{name}/opt to the configure step, but I have no idea how make would be able to write to /etc without sudo

**Comment by matt335672** [comment]
Standard way to build a lot of autotools stuff on Linux/Unix (including xrdp) is:-

```
./configure
make
sudo make install
```

The `make` is a non-privileged build. The `sudo make install` is a privileged install.

If you run `sudo make` (rather than `make`) you'll end up with directories owned by root. Then a normal `make` will not be able to write to those directories. in #2160, you've done exactly that.

Does that make sense?

**Comment by paulb39** [comment]
Thanks Matt, that makes sense, and I was able to compile and install it now.

**Comment by matt335672** [comment]
Thanks for letting me know. I'll close your two build-related issues.
