### ISSUE TITLE
new Openssl issue.. take a look..

### ISSUE THREAD

**Issue by blackcrack** [neutrinolabs/xrdp#2179]
Hi Metalefty,

take a look:  
https://thehackernews.com/2022/03/new-infinite-loop-bug-in-openssl-could.html
german text, you could take translate.google.com
https://winfuture.de/news,128613.html
https://www.heise.de/news/Sicherheitsluecke-Praeparierte-TLS-Zertifikate-koennen-OpenSSL-Systeme-gefaehrden-6550820.html?wt_mc=rss.red.ho.ho.atom.beitrag.beitrag
https://www.linux-magazin.de/news/openssl-braucht-patch/

best

p.s. if you have read, can you close this issue :)

**Comment by matt335672** [comment]
Thanks for the heads-up @blackcrack 

We dynamically link with OpenSSL, so it's really up to the distro maintainers to roll out the patch rather than us. Also, for a server, this particular problem can only be invoked by a client certificate, and those aren't supported by TLS on xrdp.

I'll close this now. Thanks again.
