### ISSUE TITLE
Session disconnects, can't reconnect during Ubuntu system upgrade 

### ISSUE THREAD

**Issue by jpmorrison** [neutrinolabs/xrdp#2245]
Connected to Ubuntu 20.04 with MS RDP. Xrdp was installed from Ubuntu repositories

Ran  `do-release-upgrade -d ` in a terminal window and the RDP session dropped.
Reconnecting shows the log/login prompt - after logging in the session is dropped again.

Not sure which logs are useful 
/var/log/auth,log
```
May  1 15:54:19 ubuntu-test xrdp-sesman[2269689]: pam_unix(xrdp-sesman:session): session opened for user jmorrison(uid=1000) by (uid=0)
May  1 15:54:19 ubuntu-test systemd-logind[4244]: New session c19 of user jmorrison.
May  1 15:54:20 ubuntu-test systemd-logind[4244]: Failed to restore VT, ignoring: Bad file descriptor
May  1 15:54:21 ubuntu-test xrdp-sesman[2269689]: pam_unix(xrdp-sesman:session): session closed for user jmorrison
May  1 15:54:21 ubuntu-test systemd-logind[4244]: Session c19 logged out. Waiting for processes to exit.
May  1 15:54:30 ubuntu-test systemd-logind[4244]: Removed session c19.
```

**Comment by bmullan** [comment]
So were you trying to upgrade the remote Ubuntu from 20.04 to 22.04 over an
RDP connection ?

*do-release-upgrade -d*
>

which is what that command would do?

Did I read your email right?

brian

**Comment by matt335672** [comment]
I think this is a consequence of two things:-
1) sesman is not currently restartable (#800). This is being worked on, but is a major change (see #1961).
2) Systems using `systemd --user` don't allow more than one graphical session per user. This isn't something we can work around in xrdp, but it might be possible by using containerised desktops.

When xrdp is upgraded, it will need to be stopped and restarted. This leaves an orphaned session (point 1). Because this session is active according to systemd however, you will be unable to start a new one (point 2).

I can understand you really want to connect to the old session however, to see how things have gone. Have you got another machine running with a graphical login available?

**Comment by matt335672** [comment]
No response from OP - closing
