### ISSUE TITLE
x11rdp version?

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xrdp#227]
AFAIK, X11rdp has no explicit version number now.  `X11RDPVER` is still 0.7.0 in [`rdp.h` in v0.8.0 tag](https://github.com/neutrinolabs/xrdp/blob/v0.8.0/xorg/X11R7.6/rdp/rdp.h#L93).

X11rdp in v0.7 branch and v0.8 branch have the same version number 0.7.0 but they're different.  It is confusing.  In FreeBSD case, I have to explain FreeBSD port committers why they have the same version number and what is the difference between them when I want to register X11rdp package. It makes difficult to make and register a package of X11rdp.  

Do you have a plan to sync X11RDPVER to xrdp's version written in [xorg/X11R7.6/rdp/rdp.h](https://github.com/metalefty/xrdp/blob/devel/xorg/X11R7.6/rdp/rdp.h#L92)?

**Comment by jsorg71** [comment]
I updated the version in devel and v0.8 branch.
devel being 0.9.0 and v0.8 to 0.8.1.
We can't include config_ac.h in rdp.h because it's not built with autotools so the version are separate for now.  This version problem with X11rdp will go away with the driver model because that will be a standard build components.  So I guess manual version changes for now unless someone has a better idea.

**Comment by metalefty** [comment]
Thanks for your work. Manual version bumping is better than nothing.
This is a temporary issue until xorg driver fully deprecate x11rdp.
