### ISSUE TITLE
[FEATURE] Request XRDP works with UDP 

### ISSUE THREAD

**Issue by ikhwanperwira** [neutrinolabs/xrdp#2277]
I'm wondering if you can make XRDP works with UDP. We know UDP is not reliable protocol, but atleast it's simple protocol that doesn't have many packet header. Hence, it will make fast transmission that make refresh rate of graphic is faster I think.

Maybe many or all XRDP client doesn't support UDP, but let me try if I can make such XRDP UDP based client. The purpose of this request is to priority of faster transmision data at cost of quality so I can play game with XRDP 🤣 ,

**Comment by hardening** [comment]
Don't wanna talk for Xrdp guys, but RDP over UDP is not trivial at all, that's a complex and very long term project.

**Comment by metalefty** [comment]
TCP is not the limiting factor in xrdp's frame rate or smoothness at all for the moment.  In other words, we have not hit the performance limits of TCP. The biggest factor is lacking of more effective graphic compressions than RFX. @Nexarian is working hard to introduce such much more effective compressions.

Please don't think short-circuitted using UDP instead of TCP makes everything faster.  UDP is not a magic tool for speed.

If what you really want is "smoother frame rates in xrdp", you do not need to specify to us how to do that.

See also #1561.
