### ISSUE TITLE
RHEL | XRDP | KDE session slowness

### ISSUE THREAD

**Issue by AbinayaSandhiyaM** [neutrinolabs/xrdp#2302]
Hi Team,

We have been using XRDP 0.9.16 on our 1000+ Linux RHEL machines.

Facing KDE Session freeze issue.
could you please let us know below details.

1. Is there any bandwidth to use KDE session on one machine
2. Any configuration changes needed to handle sever load on XRDP session
3. Does this issue has fix on any latest version of XRDP version , if yes what changes done from your end.
4. KDE freeze issue is not permanent issue but still when the issue occurs need to kill the session manually and starts the new one - this makes hard to user KDE on xrdp 

Any help/suggestion would be appreciated. 

Thanks.

**Comment by matt335672** [comment]
Hi @AbinayaSandhiyaM 

We've not had any such problems reported.

When the freeze happens, are you able to use a tool like `iftop` to see whether bandwidth is definitely an issue?

**Comment by AbinayaSandhiyaM** [comment]
Hi Matt,

Thanks for your quick response!

As per our understanding there are users who all are using XRDP with KDE session facing freeze issue when the server loads goes high.

Now the problem is not able to reuse the same session even server load gets fixed.

Restarting the xrdp service/kill the old xrdp process would help to solve the issue but still we would like to know the solution for this xrdp reconnection without restart/kill the session.

**Comment by matt335672** [comment]
I still don't quite understand your problem here.

Can you be clearer on what "server load goes high" means? Are you running out of CPU, memory, or network bandwidth?

You might also want to check your system logs when the problem occurs. If you're running out of memory, the Linux OOM killer will almost certainly be terminating some of your KDE processes which won't be good.

Your version of RHEL may allow you to set per-user limits on resource usage to prevent this happening, but I don't know anything about that. You can look that up as well as I can.

**Comment by matt335672** [comment]
No further input - closing
