### ISSUE TITLE
xrdp does not work using Ubuntu 22.04 Desktop

### ISSUE THREAD

**Issue by PaulRicharte** [neutrinolabs/xrdp#2480]
I'm using Windows 10's Remote Desktop Connection to connect. Xorg isn't working at all and xvnc produces this error:

```
VNC error - problem connecting
some problem
Error connecting to user session
```

In Ubuntu, the log of the xrdp status is:

```
xrdp[4221]: [ERROR] VNC error 1 after security negotiation
xrdp[4221]: [ERROR] VNC error before sending share flag
xrdp[4221]: [ERROR] VNC error before receiving server init
xrdp[4221]: [ERROR] VNC error before receiving pixel format
xrdp[4221]: [ERROR] VNC error before receiving name length
xrdp[4221]: [ERROR] VNC error before receiving name
xrdp[4221]: [INFO ] VNC error - problem connecting
xrdp[4221]: [ERROR] xrdp_wm_log_msg: Error connecting to user session
xrdp[4221]: [INFO ] Error connecting to user session
```

xrdp version is 0.9.21.1
tightvncserver is installed

**Comment by matt335672** [comment]
It looks lile the X server is running, but getting killed, possibly because the session is ending prematurely.

If you're trying to use GNOME, you've got a couple of possible incompatibilities:-
- You need to be requesting at least 24-bit colour from the RDP client.
- I don't believe tightvnc supports GLX by default (I could be wrong on this). GNOME requires GLX support. Unless you absolutely have to use tightvnc, remove it and install `tigervnc-standalone-server` instead.

If none of that is that case, here are some other questions for you:-
- What does the `xrdp-sesman.log` look like for the connection attempt?
- Which desktop are you trying to connect to?
- What is the output of `update-alternatives --display x-session-manager`

**Comment by PaulRicharte** [comment]
Hello,
The client was asking for 32-bit colour. TightVNC may have been the issue then!
Unfortunately, I've made a clean install of Ubuntu so any log is lost. I'm now using NoMachine as an alternative to xrdp.

**Comment by matt335672** [comment]
Thanks for the update.

Are we OK to close this one then?

**Comment by fxbrit** [comment]
hello! I'm having some issues with Ubuntu 22.04 as well:
- I'm using `xfreerdp /v:<IP_Address>` on the client, a macOS machine with XQuartz installed.
- I'm trying to connect to Gnome.
- `update-alternatives --display x-session-manager` shows:

```
x-session-manager - auto mode
  link best version is /usr/bin/gnome-session
  link currently points to /usr/bin/gnome-session
  link x-session-manager is /usr/bin/x-session-manager
  slave x-session-manager.1.gz is /usr/share/man/man1/x-session-manager.1.gz
/usr/bin/gnome-session - priority 50
  slave x-session-manager.1.gz: /usr/share/man/man1/gnome-session.1.gz
/usr/bin/openbox-session - priority 40
  slave x-session-manager.1.gz: /usr/share/man/man1/openbox-session.1.gz
```
- `xrdp-sesman.log` shows (among others):

```
[20221222-12:11:54] [ERROR] There is no X server active on display 10
[20221222-12:11:54] [ERROR] A fatal error has occured attempting to start the window manager on display 10, aborting connection
[20221222-12:11:54] [WARN ] Window manager (pid 3020, display 10) exited quickly (0 secs). This could indicate a window manager config problem
```

is there anything I should be doing differently?

**Comment by matt335672** [comment]
@fxbrit - your problem appears to be in the "There is no X server active message".

This is a completely different issue from the OP issue. Make sure `xorgxrdp` is installed. If that's not it feel free to open a new issue.

**Comment by fxbrit** [comment]
sorry about the noise, I will open a new issue.
