### ISSUE TITLE
Polkit issues on remote sessions

### ISSUE THREAD

**Issue by Pipodi** [neutrinolabs/xrdp#2542]
When I'm on a remote session to my laptop, it seems that Polkit (or I suppose it is the cause) won't allow me to do privileged actions, it doesn't even ask me administrative passwords with the classic popup (like when unlocking the keyrings), which it's the case if I do the same actions directly on the physical machine.

For example:

![image](https://user-images.githubusercontent.com/2904611/217786910-61238cf6-6594-4b81-a11e-5ac07dcc948d.png)

Bitwarden stays like this, no prompt whatsoever.

But if I run `sudo bitwarden-desktop --no-sandbox`:

![image](https://user-images.githubusercontent.com/2904611/217787865-c2371659-140f-49c3-b584-bd128e26229d.png)

Tried to do some .pkla like this:

```
ls -lash /etc/polkit-1/localauthority/50-local.d/50-xrdp.pkla 
4,0K -rw-r--r-- 1 root root 80  9 feb 10.54 /etc/polkit-1/localauthority/50-local.d/50-xrdp.pkla
```
```
cat /etc/polkit-1/localauthority/50-local.d/50-xrdp.pkla 
[Allow everything]
Identity=unix-user:*
Action=*
ResultAny=yes
```

Restarted polkit.service and even rebooted the machine, no result.

Some ideas? Working on a fresh Manjaro with XFCE.

**Comment by matt335672** [comment]
Your .pkla file won't work on Manjaro. It will work on Ubuntu/Debian, as these use polkit 0.105. Versions of polkit later than this use Javascript-based rules. Here are some pointers for you:-

- Arch wiki : https://wiki.archlinux.org/title/Polkit
- Polkit documentation : https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html
- [#1889](/neutrinolabs/xrdp/issues/1889) (SuSE, but relevant to you I believe)

**Comment by Pipodi** [comment]
Ok, thanks a lot.

This is the .rules file I came up with:

```
cat /etc/polkit-1/rules.d/10-xrdp.rules 
polkit.addRule(function(action, subject) {
	if (subject.user == "pipodi") {
		return polkit.Result.YES;
	}
});
```

But I have the same result with Bitwarden. In the `rules.d` folder there is another .rules file, `99-manjaro.rules`:

```
polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.freedesktop.udisks2.") == 0 && subject.isInGroup("wheel")) {
        return polkit.Result.YES;
    }
});

polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.login1.power-off" ||
        action.id == "org.freedesktop.login1.reboot" ||
        action.id == "org.freedesktop.login1.hibernate" ||
        action.id == "org.freedesktop.login1.suspend") {
        return polkit.Result.YES;
    }
});

polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.upower.hibernate" ||
        action.id == "org.freedesktop.upower.suspend") {
        return polkit.Result.YES;
    }
});

/* Allow users of network group to use blueman feature requiring root without authentication */
polkit.addRule(function(action, subject) {
    if ((action.id == "org.blueman.network.setup" ||
         action.id == "org.blueman.dhcp.client" ||
         action.id == "org.blueman.rfkill.setstate" ||
         action.id == "org.blueman.pppd.pppconnect") &&
        subject.isInGroup("network")) {
        return polkit.Result.YES;
    }
});

```

I don't see something in here that could block or overwrite my rule.

**Comment by matt335672** [comment]
Your rule looks fine to me.

All of those rules you've posted return `polkit.Result.YES` so they're allowing actions rather than blocking them. They can't be interfering with your action by the look of it.

So it's either not polkit, or something else is going on here. There are some hints on the Arch wiki link I posted above about logging. That might help to determine what's going on.

**Comment by alexhorner** [comment]
Seems related to https://github.com/neutrinolabs/xrdp/discussions/2306 ?

**Comment by Pipodi** [comment]
Ok, somehow now it works, but it is VERY slow to show the login form and to login too. Tried to run via console, no strange warning/error whatsoever. On local session it is very snappy and responsive.

**Comment by matt335672** [comment]
Might be excessive logging. See if you've enabled debug logging.

**Comment by Pipodi** [comment]
If you mean on XRDP, no, I have no debug logging enabled.

**Comment by matt335672** [comment]
There aren't a lot of tunables in xrdp that can make it VERY slow. If you're running with default settings you should get reasonable behaviour.

Off the top of my head:-

- Could be network issues. xrdp is very sensitive to latency.
- Your graphical session is making intense use of hardware acceleration locally (or has a lot of screen real-estate), and is struggling to move the pixels over the network to the RDP client.

Because you say the login screen is taking a while to appear, I'd lean to looking at the network. The login screen is simple and doesn't involve a lot of pixels moving about.

All of the below assumes you're running on the same LAN segment for both client and server.

Easy things are:-
- If you're running over WiFi for either (or both) machines, try cables instead if this is possible.
- Check the system log for any unexplained activity. You may well (for example) find the network interface is flapping which isn't always obvious when using the machine for browsing. I've seen this more than once on RealTEK NICs in laptops.

After that it gets harder, as you'll need to use tools like iperf3 and ping to measure systemic behaviour.
