### ISSUE TITLE
clipboard doesn't work after a while from Windows 10 RDP client

### ISSUE THREAD

**Issue by vongillus** [neutrinolabs/xrdp#2596]
Hi,

I am using quite intensively XRDP on my Linux systems to access them remotely (thanks for this amazing work by the way). Since a few months without changing anything on the XRDP side, I begun to lose clipboard functionality. Sometimes from the client to the server only, sometimes from the server to the client, sometimes both sides I think. If I close the RDP connection and reconnect, sometimes I get the clipboard back but quite often I am forced to completely close the session.

On the server side, when it doesn't work I get this kind of messages:

xrdp-chansrv[9394]: [ERROR] clipboard_event_selection_request: unknown target text/plain;charset=utf-8

I suspect a problem from the Windows client side since I notice this with different OS targets (Ubuntu, RHEL7, RHEL8) and also I didn't change anything on the XRDP side. But if anyone could tell me how to "prove" or debug that, it would be really nice.

Also, would there be a way to properly restart xrdp-chansrv without closing the session?

The version of XRDP I am using is the one from the distribution: 0.9.21 on RHEL8 or RHEL7 and 0.9.17 on Ubuntu 22.04. Client is Windows 10 LTSC 1809.

Thanks a lot

**Comment by matt335672** [comment]
A couple of possibilities:-
1) Some clipboard bugs were fixed in v0.9.18 ([#1992](neutrinolabs/xrdp#1992), [#1997](neutrinolabs/xrdp#1997)). One of these was related to hanging, so you may well see different behaviour on Ubuntu 22.04.
2) Some versions of GNOME broke the clipboard in lots of ways. One of these is the [RHEL 8 version](/neutrinolabs/xrdp/issues/1994#issuecomment-918042018). On that OS, if (and only if) you're using GNOME, you probably need to set `UseNautilus3FlistFormat=true` in `/etc/xrdp/sesman.ini`
1) There are some bugs in chansrv which can break it when you're using shared drives. Those are all fixed by 0.9.21, at least as far as I know, but you may have found another one. If you're using shared drives, you can try disabling that feature for a bit.
2) On a reconnect, if another session is already connected, the clipboard won't work as chansrv is already occupied. We're looking at ways to fix this.

To restart chansrv without restarting the session:-
1) Kill it. You'll end up with a zombie process which you can ignore.
2) Unmount the shared filesystem with `fusermount -u ~/thinclient_drives`
3) Run `xrdp-chansrv` is a terminal window in the session.
4) Disconnect and reconnect from the RDP session.

You can use the `xclip` utility to see what the X clipboard contains. `xclip -selection clipboard -o -t TARGETS` will tell you what kind of data is on the clipboard, and `xclip -selection clipboard -o -t <atom>` will tell you what's held for a particular atom.

Hope that's of some use.
