### ISSUE TITLE
Error loading libvnc.so in XRDP - Feedback

### ISSUE THREAD

**Issue by zscaorui** [neutrinolabs/xrdp#2690]
Subject: Error loading libvnc.so in XRDP - Feedback

Dear neutrinolabs,

I am writing to provide feedback regarding an issue I encountered while using XRDP. I am experiencing difficulties with the loading of the libvnc.so library as specified in the xrdp.ini configuration file. The error message suggests adding a valid entry such as "lib=libxrdp-vnc.so" or a similar valid entry.

Here are the details of the issue:

Error message: "connecting to sesman on 127.0.0.1:3350 sesman connect ok sending login info to session manager. Please wait... login successful for user caorui on display ll error loading libvnc.so specified in xrdp.ini. please add a valid entry like lib=libxrdp-vnc.so or similar."

Steps to reproduce:

Install and configure XRDP on a CentOS 7 system.
Attempt to establish a remote desktop connection using XRDP.
Encounter the above-mentioned error message.
System information:

Operating System: CentOS 7.9
XRDP version: xrdp.x86_64 1:0.9.22-3.el7 
Installed VNC-related packages: 
gtk-vnc2.x86_64                         0.7.0-3.el7                    @anaconda
gvnc.x86_64                             0.7.0-3.el7                    @anaconda
libvncserver.x86_64                     0.9.9-14.el7_8.1               @updates 
libvncserver-devel.x86_64               0.9.9-14.el7_8.1               @updates 
tigervnc.x86_64                         1.8.0-25.el7_9                 @updates 
tigervnc-icons.noarch                   1.8.0-25.el7_9                 @updates 
tigervnc-license.noarch                 1.8.0-25.el7_9                 @updates 
tigervnc-server.x86_64                  1.8.0-25.el7_9                 @updates 
tigervnc-server-minimal.x86_64          1.8.0-25.el7_9                 @updates 

I have verified that the libvnc.so library is not present in the system.
I have installed the tigervnc-server package as per the official XRDP installation instructions.
The error occurs consistently whenever attempting to connect via XRDP.
Please let me know if you require any additional information or if there are specific logs or configurations that would be helpful for debugging this issue. I appreciate your assistance in resolving this problem.

Thank you for your attention to this matter.

Sincerely,
zscaorui
zscaorui@stumail.nwu.edu.cn

**Comment by alfredojoseneto** [comment]
The solution provide in issue #2689 solves the problem by default installation doesn't brings the **libvnc.so** module that is necessary for complete functionality of xrdp throw windows rdp remote access.

**Comment by matt335672** [comment]
Hi all,

We've had multiple threads raised here about the same issue.

I'd encourage the participants in this thread to look at #2678, in particular [this post](/neutrinolabs/xrdp/discussions/2678#discussioncomment-5937960) regarding a significant issue with 0.9.22-4

Please add further comments and queries to #2678

**Comment by n0uec** [comment]
Those threads did not work on my RHEL 8 system. The fix was found here:
https://github.com/neutrinolabs/xrdp
For RHEL 8, do: 
$ sudo yum install epel-release
$ sudo yum install xrdp

The RDP from my Windows laptop works now. So much better than using VMware Horizon Client!

**Comment by deardeer7** [comment]
Hello, I encountered the same issue in **Ubuntu 22.04** and found a solution suggesting the use of a specified version like xrdp-0.9.22. How can I address this on an Ubuntu device?

here is the log:
![image](https://github.com/neutrinolabs/xrdp/assets/42965045/6ae3d458-1a58-433d-978d-3bf6865b1c69)

**Comment by matt335672** [comment]
@deardeer7 - this isn't the same issue. This issue is an EPEL packaging issue which doesn't affect Ubuntu.

You might coming across #1986. If so, check LD_BIND_NOW isn't set in your global environment.

Other than that, Ubuntu don't routinely rebuild xrdp packages except for explicit security problems. You'll have to either:-
1) Trying using the xorgxrdp backend instead of the VNC backend. You'll need to `apt install xorgxrdp` and make some config changes.
2) Rebuild it yourself.
3) Find a source you can trust on the Internet for later versions of xrdp. As a project we don't recommend any such sources.

**Comment by deardeer7** [comment]
ok, thanks. i fixed my bug.在 2024年3月6日，19:35，matt335672 ***@***.***> 写道：﻿
@deardeer7 - this isn't the same issue. This issue is an EPEL packaging issue which doesn't affect Ubuntu.
You might coming across #1986. If so, check LD_BIND_NOW isn't set in your global environment.
Other than that, Ubuntu don't routinely rebuild xrdp packages except for explicit security problems. You'll have to either:-

Trying using the xorgxrdp backend instead of the VNC backend. You'll need to apt install xorgxrdp and make some config changes.
Rebuild it yourself.
Find a source you can trust on the Internet for later versions of xrdp. As a project we don't recommend any such sources.
