### ISSUE TITLE
xrdp crashes or exits after a rogue incoming connection

### ISSUE THREAD

**Issue by yurivict** [neutrinolabs/xrdp#2710]
I left the xrdp port exposed on the internet.

This leads to xrdp dying about every day with this written into log:
```
May 29 18:42:30 yv xrdp[17069]: [ERROR] SSL_accept: I/O error
May 29 18:42:30 yv xrdp[17069]: [ERROR] trans_set_tls_mode: ssl_tls_accept failed
May 29 18:42:30 yv xrdp[17069]: [ERROR] xrdp_sec_incoming: trans_set_tls_mode failed
May 29 18:42:30 yv xrdp[17069]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
May 29 18:42:30 yv xrdp[17069]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed 
May 29 18:42:30 yv xrdp[17069]: [ERROR] xrdp_iso_send: trans_write_copy_s failed 
May 29 18:42:30 yv xrdp[17069]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
```

Nobody was using RDP at this time, so it looks like some sort of port scanner hitting this port and xrdp crashing or exiting after this.

xrdp-0.9.22
FreeBSD 13.2

**Comment by matt335672** [comment]
First thing to say, is:-

**Never expose ANY RDP server (including xrdp) to the internet in this way. The protocol isn't safe enough to support this.**

These days there's no excuse not to use a VPN of some sort to protect sensitive resources. Since you've already got point-to-point connectivity, consider either OpenVPN or wireguard as these are straightforward to set up with the server end on the xrdp machine. Then configure xrdp (and maybe other services) to listen on the VPN endpoint.

Other than that, thanks for the report but I'm not sure what we can do about this. I'll try running a fuzz test on a machine here and see if I can find anything.

**Comment by matt335672** [comment]
See also #2040 which appears to cover the logging above.

**Comment by matt335672** [comment]
I've now run a fuzzer on xrdp for an hour (with forking disabled) and got no crashes or similar. There are however plenty of log messages similar to the above.

I'm closing this - I think it's adequately explained by #2040 / #2505 and I can find no other immediate problems.

**Comment by alexandrunic** [comment]
Worked for me after performing the following:
1.  Commented the following line "TerminalServerUsers=tsuers" in file /etc/xrdp/sesman.ini
2. systemctl restart xrdp-sesman
3. remote desktop and login with **root acoount** on the remote machine

**Comment by matt335672** [comment]
@alexandrunic - can you add more detail on exactly what the above procedure solves? By default it's not possible to log in with root to xrdp.

**Comment by NickNevzorov** [comment]
> Worked for me after performing the following:
> 
> 1. Commented the following line "TerminalServerUsers=tsuers" in file /etc/xrdp/sesman.ini
> 2. systemctl restart xrdp-sesman
> 3. remote desktop and login with **root acoount** on the remote machine

Thanks! Work for me on Raspi 4 with last updates
