### ISSUE TITLE
Gnome keyring was not unlocked

### ISSUE THREAD

**Issue by dpkristensen** [neutrinolabs/xrdp#2776]
### xrdp version

0.9.17

### Detailed xrdp version, build options

~~~
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 3.0.2 15 Mar 2022
~~~

### Operating system & version

Ubuntu 22.04

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

GNOME

### Environment xrdp running on

Physical: 00:02.0 VGA compatible controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 21)

### What's your client?

Windows 11 RemoteDesktop

### Area(s) with issue?

Session manager (sesman)

### Steps to reproduce

# Start up RDP session
# Launch VS code (no extensions)
# Observe popups for "gnome-keyring was not unlocked" with prompts to enter password

### ✔️ Expected Behavior

Gnome keyring should be unlocked when logging in remotely.

### ❌ Actual Behavior

Gnome keyring was not unlocked

### Anything else?

There's quite a lot of rabbit holes on this, but I found the following information that zero'd in on the problem:

* Christian Pernegger reported this issue to the Debian maintainers in 2016: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818936
* This references a lightdm PAM configuration file at https://github.com/davvid/lightdm/blob/master/debian/lightdm.pam

My out-of-the-box /etc/pam.d/xrdp-sesman looks like this:
~~~~
#%PAM-1.0
auth required pam_env.so readenv=1
auth required pam_env.so readenv=1 envfile=/etc/default/locale
@include common-auth
@include common-account
@include common-session
@include common-password
~~~~

To fix the issue, I added these lines:
* In common-auth: `auth optional pam_gnome_keyring.so`
* In common-session: `session optional pam_gnome_keyring.so auto_start`

VS Code simply exposes the issue, because it uses evolution under the hood, which is why it's not related to any specific VS code extension.  It seems the issue is related to how XRDP isn't enabling the necessary libraries.  Obviously there's a lot of other stuff that could be added in here, like libkwallet, etc...

Is there an easier way to add these things to the template config file installed with xrdp?  Check for dependencies at install and then add them?  Most users are going to follow all the terrible advice on the internet and do things like change it to an empty password, launch apps with an option to force plaintext password stores, etc...

**Comment by matt335672** [comment]
Hi @dpkristensen 

I've had a good look into this.

Firstly; A better and more recent link to the Debian config for lightdm is here in Canonical's area:-

https://github.com/canonical/lightdm/blob/main/debian/lightdm.pam

The relevant lines are:-

```
-auth    optional        pam_gnome_keyring.so
-auth    optional        pam_kwallet.so
-auth    optional        pam_kwallet5.so
```

and:-

```
-session optional        pam_gnome_keyring.so auto_start
-session optional        pam_kwallet.so auto_start
-session optional        pam_kwallet5.so auto_start
```

You'll notice that this uses `-` signs in front of relevant lines and also has a `pam_kwallet5.so`. The `-` signs suppress errors being reported where the modules aren't installed. AFAICT, `pam_kwallet.so` is the Qt4-based kwallet interface. Qt4 has been unsupported since 2015.

Debian already has a templating mechanism for this sort of thing, accessed via the privileged `pam-auth-update` command.  To my mind `pam-auth-update` should embed the support for the GNOME keyring, but it seems this isn't the case - only password changes are supported via templating. Here's `/usr/share/pam-configs/gnome-keyring` from the `libpam-gnome-keyring` package (emphasis mine):-

<pre>
pam_gnome_keyring for Debian
----------------------------

The default PAM configuration for GDM and gnome-screensaver already 
uses pam_gnome_keyring. Password change is also implemented through the 
global PAM configuration.

<b>If you want to start gnome_keyring from another display manager, you 
need to add the following lines to the corresponding /etc/pam.d/?dm 
file:
    auth    optional        pam_gnome_keyring.so
    session optional        pam_gnome_keyring.so  auto_start</b>

 -- Josselin Mouette <joss@debian.org>, Sun, 25 Nov 2007 11:53:10 +0100
</pre>


Pulling all this together, I see no reason why the xrdp Debian PAM module can't include these lines:-

```
-auth    optional        pam_gnome_keyring.so
-auth    optional        pam_kwallet5.so
```

and

```
-session optional        pam_gnome_keyring.so auto_start
-session optional        pam_kwallet5.so auto_start
```

This will fix the GNOME and KDE keyrings I think.

At the same time we can pull in this patch from the Debia Salsa repository. They haven't asked for it to be upstreamed, but doing so makes more sense for users building from source:-

https://salsa.debian.org/debian-remote-team/xrdp/-/blob/master/debian/patches/fix-environment.diff

There's more in the lightdm config we could adopt, but let's start with the simple, testable stuff.

How does that sound @dpkristensen ?

**Comment by dpkristensen** [comment]
Sure.  I have updated my system such that etc/pam.d/xrdp-sesman contains:
~~~~
#%PAM-1.0
auth required pam_env.so readenv=1
auth required pam_env.so readenv=1 envfile=/etc/default/locale
@include common-auth
-auth optional pam_gnome_keyring.so
-auth optional pam_kwallet5.so
@include common-account
@include common-session
-session optional pam_gnome_keyring.so auto_start
-session optional pam_kwallet5.so auto_start
@include common-password
~~~~
Not sure why it is necessary to load pam_env.so twice with a different environment; maybe so it can work in both the selected and the default locale?  If that is the case, is it necessary to do the same with the keyring/wallet libs?

In any case, XRDP works here, and I see the keyring unlocked upon logging in:
~~~~
xrdp-sesman[1520]: gkr-pam: gnome-keyring-daemon started properly and unlocked keyring
~~~~
I don't have KDE installed to test, but I can vouch for gnome at least.

**Comment by matt335672** [comment]
I'll try to answer your question. On Debian:-

- `/etc/environment` contains no locale information.
- `/etc/default/locale` contains only locale information.

This allows the `update-locale` command to update a single file.

`pam_env` only supports a single file for variables. Other system components support a directory which is scanned for config files. For example, `sudo` has  `/etc/sudoers` and `/etc/sudoers.d`. This allows for a more modular approach.

If `pam_env` supported something like `/etc/environment.d/` the second call would not be needed. This is a feature which has been requested (see linux-pam/linux-pam#122), but has not yet been implemented by the PAM team.

Does that help?

Thanks for the testing - it really helps. I'll put a PR together.

**Comment by dpkristensen** [comment]
Thanks for the knowledge, and SUPER thanks for maintaining XRDP.  This is a great tool for heterogeneous environments, and your work is used + appreciated by countless people.
