### ISSUE TITLE
Does different screen resolution mean new session?

### ISSUE THREAD

**Issue by robertalks** [neutrinolabs/xrdp#287]
Hello, I was wondering if using a different screen resolution means a new session?

example:
new session: rdestop -u test -p test 1.2.3.4 -g 800x600 (dont logout, just close the window)
re-connect to the session: rdestop -u test -p test 1.2.3.4 -g 1024x768

Now, doing this, will get me 2 sessions, one with 800x600 and another one with 1024x768, but my question is if this is normal or expected or by design? Is this a bug?

Thank you.

**Comment by metalefty** [comment]
No, what session type do you use?

**Comment by robertalks** [comment]
Xvnc for example.

**Comment by robertalks** [comment]
The setup is: xrdp -> Xvnc -> Gnome/Xfce (tested with both)

**Comment by jsorg71** [comment]
Hello,

When using Xvnc for the backend, username and size both are used to identify a session.
If I remember right, this is because you can't resize the Xvnc session after it's started.
If you want to use X11rdp for the backend, it can resize.

**Comment by robertalks** [comment]
BTW, this is not really true, Xvnc supports resizing if used with vncserver for example, something like:

vncserver -> Xvnc -> Gnome

Test this myself and you can resize the Xvnc session on the fly.

**Comment by metalefty** [comment]
Jay, for example TigerVNC supports resizing. See also #259.

**Comment by jsorg71** [comment]
Sure, we can add it to sesman and the vnc session plugin.
I'm not sure if sesman can know which Xvnc is running so what will happen if it's not TigerVNC?

**Comment by metalefty** [comment]
I'm not sure, too. It is need to be confirmed but probably nothing will happen.
One hacky way to know which Xvnc is running is to parse output of `Xvnc -version`.

**Comment by bolkedebruin** [comment]
@jsorg71 just make it configurable "AllowVncResize=1" for example (I have a small branch that has it). Resizing for VNC seems to require an extended command btw.

**Comment by proski** [comment]
What branch is that? I would be happy to test it. That's actually a big deal in my company. People have their laptops connected to a high resolution display. They start an XRDP/Xvnc session at the native resolution. Then they go to a meeting and cannot connect to their session at all because the laptop's resolution is different.

The policies for session selection seem an overkill to me. Users should be asked on the login screen if they want to connect to an existing session or create a new one. The default should be to reconnect. XRDP should try everything possible to connect to an existing session rather than consult any policies.

**Comment by coredump4** [comment]
If you click on his username, GitHub links you over to his account and you can see projects he's contributed to.  Look for xrdp and you can download his version.
Here's the link to his xrdp fork:  [https://github.com/bolkedebruin/xrdp](url)

**Comment by metalefty** [comment]
Not a bug. Xvnc cannot resize but x11rdp/xorgxrdp can resize.
Use x11rdp/xorgxrdp to reconnect from different resolution.
