### ISSUE TITLE
Microsoft Remote Desktop crashes when allow_channels is set to true

### ISSUE THREAD

**Issue by Xaymar** [neutrinolabs/xrdp#302]
**Version:** https://github.com/neutrinolabs/xrdp/commit/82614597079560ee4ec9e3c8559ff9187b464d6a

Microsofts Remote Desktop crashes when the option "allow_channels" is set to true. It seems that whatever xrdp is sending is not something that should be there. Changing any of the channels to false doesn't solve the problem.

Workaround: Set allow_channels to false.

**Comment by Xaymar** [comment]
Reencountered half a year later, thank god for open issues like these to figure out how to solve things.

**Comment by metalefty** [comment]
I'd like to clarify what is "Microsoft Remote Desktop" you talking about.
Windows' RDP client mstsc.exe?

**Comment by Xaymar** [comment]
Exactly. It's not the only one that crashes with allow_channels set to true, but it's by far the most non-crash resistent RDP client.

**Comment by blackcrack** [comment]
(suggestion)
why do you not create via qt or an other multisystem possibility , 
creating a good client ;) as garnish (delicious) for diffrent System, 
who be an bit stable and crash-resistand as the mstsc ;)
it's a point ?

keep it up ! :)

best regards
Blacky

**Comment by metalefty** [comment]
I think this is fixed by #615. Please reopen if still happen with current devel head.

**Comment by Xaymar** [comment]
I've rebuilt and tested. Last devel also fixed #207 finally. Copy & Paste doesn't work but at least it doesn't crash Microsoft Remote Desktop. Great work!

**Comment by EgoAleSum** [comment]
Encountered this today on a freshly-installed FC25 box... xrdp 0.9.2

**Comment by metalefty** [comment]
What is your client version?

**Comment by EgoAleSum** [comment]
@metalefty Microsoft Remote Desktop (for Mac) Version 8.0.39 (Build 27287)

Also, unlike my previous VM which was running on a FreeBSD host (via bhyve) and on an Atom C2750, this one runs on ESXi on a Xeon D-1521... And maybe it's because of some driver issues, but the RDP session crashes constantly: for example, when I click on certain buttons of the UI, when I select text in a textbox, etc... The OS is Fedora Workstation 25, latest updates, running LXDE. Not sure how much of this is XRDP's fault, but it's highly unstable compared with my previous experience.

**Comment by metalefty** [comment]
Is your backend VNC? If so, your issue looks like #755 rather than this.

**Comment by EgoAleSum** [comment]
I am not sure, I have just installed xrdp on Fedora and I believe it has "Xvnc" as backend (but don't quote me on that).

I've cleared my clipboard and the issue appears anyways.

**Comment by Xaymar** [comment]
Did you try compiling from source @EgoAleSum? Some distros ship an older version as stable (such as Debian, Ubuntu).

**Comment by metalefty** [comment]
@EgoAleSum 
I looked into Fedora package. Fedora defaults to Xvnc.  I believe you're using Xvnc backend.  As discussed in #755, xrdp has a problem Xvnc + clipboard and not fixed yet.  Fedora guys provide a workaround how to avoid disconnection. You should see `/usr/share/doc/xrdp/README.Fedora`.

For further discussions, let's move to #755 since your issue is most likely to #755.
