### ISSUE TITLE
epel-release missing in Fedora 40

### ISSUE THREAD

**Issue by superbonaci** [neutrinolabs/xrdp#3052]
### xrdp version

0.9.25

### Detailed xrdp version, build options

~~~
Paste the result between `~~~`.  Please DO NOT remove `~~~`!
~~~

### Operating system & version

Fedora 40

### Installation method

dnf / apt / zypper / pkg / etc

### Area(s) with issue?

Other

### Steps to reproduce

$ sudo dnf install epel-release
No match for argument: epel-release
Error: unable to find a match: epel-release

**Comment by matt335672** [comment]
@superbonaci - did you mean to post this here? I can't see the connection to xrdp ATM.

**Comment by superbonaci** [comment]
@matt335672 yes, this is a bug for https://github.com/neutrinolabs/xrdp/blob/devel/README.md because the command listed in the readme does not work, at least in Fedora 40, maybe did in Fedora 39 or other RHEL versions, so needs improvement.

**Comment by rowlap** [comment]
EPEL stands for Extra Packages for Enterprise Linux, i.e. it's a repo intended only for use on RHEL or derived distros.

https://github.com/neutrinolabs/xrdp/blob/devel/README.md#redhat--centos--fedora is mildly confusing because the heading says "RedHat / CentOS / Fedora" but the following text says "On RedHat and CentOS".

**Comment by superbonaci** [comment]
So it means "On RedHat and CentOS only", any chance to edit that?
