### ISSUE TITLE
X11rdp build step missing information

### ISSUE THREAD

**Issue by superbonaci** [neutrinolabs/xrdp#3064]
### xrdp version

0.9.25

### Operating system & version

Fedora 40

### Actual results

In this wiki page:
https://github.com/neutrinolabs/xrdp/wiki/Building-on-Fedora-19-&-20

the step "this is X11rdp build step" is not clean what's for, there's no `xorg` folder inside xrdp.

**Comment by matt335672** [comment]
@superbonaci - I'm very happy for Wiki users to edit pages, but please don't delete them or rename them. It destroys the editing history, and it also breaks links to the pages (as it did in this case). Also, it's a really bad idea to put a '&' character into a wiki page tile as it can get very confusing.

I've restored the old page and put your edits back on top.

**Comment by superbonaci** [comment]
@matt335672 wait a second, it means fedora 19 20 or fedora 39 40?

**Comment by matt335672** [comment]
Well, you'd renamed this page:-

Building-on-Fedora-19---20.mediawiki

as this:-

Building-on-Fedora-19-&-20.mediawiki

I agree that neither page is a good title.

You can always create a new page Building-on-Fedora.mediawiki without any version number. Within that page:-
1) you can link to the old page so that it can still be found
2) you can say what version(s) the current page is applicable to.

Then on the index page you can link to the new page.
