### ISSUE TITLE
Need to fix the delay, that is not needed if ibus is already started

### ISSUE THREAD

**Issue by JulyIghor** [neutrinolabs/xrdp#3080]
https://github.com/neutrinolabs/xrdp/blob/98d0003715be1e0693817f49925d48b558df69bb/sesman/chansrv/input_ibus.c#L224

**Comment by matt335672** [comment]
@JulyIghor - this was discussed earlier. See [this comment](https://github.com/neutrinolabs/xrdp/issues/1990#issuecomment-2061373859) in #1990 

Are there any problems that this delay is causing you?

**Comment by JulyIghor** [comment]
> Are there any problems that this delay is causing you?

Yes, I wish it to work instantly, by commenting the line I have zero issues. It would be better to fix it with no sleep, and if it fails, retry once per second 3 times if needed.

**Comment by JulyIghor** [comment]
I use this bash code, it fixes the issue without full desktop environment. I see no reason for the sleep to be in the c++ code.

```
IBUS_ADDRESS=""
while [ "$IBUS_ADDRESS" = "" ] || [ "$IBUS_ADDRESS" = "(null)" ]; do
    sleep 1
    IBUS_ADDRESS=$(ibus address)
done
export IBUS_ADDRESS
```

**Comment by matt335672** [comment]
Thanks @JulyIghor - that's useful particularly the bash code.

I've spend a bit of time looking into this, and I think I can see what's happening here.

The first thing to say is that chansrv is not started on the same codepath as `startwm.sh`. chansrv is started directly from sesexec and no scripts are run when it is started - not even user login scripts. This is described very briefly [here](https://github.com/neutrinolabs/xrdp/wiki/SessionManagementArchitecture#session-process-management)

So your bash code above can't be having a direct effect on chansrv - at least not that I can see.

We've got two processes which need to communicate being started in two separate execution threads:-
1. chansrv is started directly from sesexec.
2. The IBus daemon is started from the windowe manager scripts invoked by `startwm.sh`

I suspect what's happening here is there's a race condition. There's probably less scripting on your system because of your minimal environment. When chansrv gets to the code we're discussing the daemon is already up. On @seflerZ's system there are more scripts (and maybe services) being run before the daemon is started, so a wait is required.

Your bash code above is calling the ibus utility. I've had a look at this, and it's written in Vala. In particular, `ibus address` invokes this function:-
https://github.com/ibus/ibus/blob/4059b9f43f4505c855677abde1b59fc13241ca58/tools/main.vala#L793-L798

The vala code calls into this C function (if I'm reading it right):-

https://github.com/ibus/ibus/blob/4059b9f43f4505c855677abde1b59fc13241ca58/src/ibusshare.c#L195-L248

We can call that function directly from input_ibus.c. I'm thinking a patch along these lines might be worth adding to that code. In your environment it shouldn't have any effect.

```diff
--- a/sesman/chansrv/input_ibus.c
+++ b/sesman/chansrv/input_ibus.c
@@ -220,8 +220,21 @@ xrdp_input_unicode_init(void)
         return 0;
     }
 
-    /* Wait becasue ibus daemon may not be ready in first login. Do we have a flag to avoid busy waiting? */
-    sleep(3);
+    /* Wait because the ibus daemon may not be ready on first login */
+    const char *addr = ibus_get_address();
+    unsigned int cnt = 0;
+    while (!addr && cnt < 10)
+    {
+        usleep(500 * 1000); // half a second
+        addr = ibus_get_address();
+        ++cnt;
+    }
+    if (!addr)
+    {
+        LOG(LOG_LEVEL_ERROR,
+            "xrdp_ibus_init: Timed out waiting for iBus daemon");
+        return 1;
+    }
 
     LOG(LOG_LEVEL_INFO, "xrdp_ibus_init: Initializing the iBus engine");
     ibus_init();
```

I haven't tested the above!

@seflerZ - any thoughts on this?

Also, for both of you, if we're going to add a timeout, should it be configurable do you think?

**Comment by JulyIghor** [comment]
Looks good, that way we get no delay if possible

**Comment by seflerZ** [comment]
@matt335672 I tried to do the status check before but failed (very confusing) in another way. It's definitely welcome if this patach works. I'll try it later today.  

As for the timeout, I don't think it's necessary just because it makes things complex. We need the feature not the configuration. A moderate timeout is enough.

**Comment by matt335672** [comment]
Thanks both.

@seflerZ - I'll wait for your feedback. You know a lot more about this area than I do, so I value your testing input.

**Comment by seflerZ** [comment]
Thanks @matt335672 . I've applied the patch and had it tested. It works well !

**Comment by seflerZ** [comment]
Thanks @matt335672 . I've applied the patch and had it tested. It works well !

**Comment by matt335672** [comment]
Thanks @seflerZ .

I'll put a PR together which will automatically close this issuer when it's merged.

**Comment by JulyIghor** [comment]
I think those lines need to be removed,
```
    g_signal_connect(factory, "enable", G_CALLBACK(xrdp_input_ibus_engine_enable), NULL);
    g_signal_connect(factory, "disable", G_CALLBACK(xrdp_input_ibus_engine_disable), NULL);
```
they are already connected to engine correctly later in the code


```
(process:1673): GLib-GObject-CRITICAL **: ../../../gobject/gsignal.c:2533: signal 'enable' is invalid for instance '0x114a740' of type 'IBusFactory'
(process:1673): GLib-GObject-CRITICAL **:  ../../../gobject/gsignal.c:2533: signal 'disable' is invalid for instance '0x114a740' of type 'IBusFactory'
    
```

**Comment by JulyIghor** [comment]
also this may be something never used, since we pushing keys, not listening them

`g_signal_connect(engine, "process-key-event", G_CALLBACK(engine_process_key_event_cb), NULL);`

**Comment by seflerZ** [comment]
@JulyIghor Well, I considered. But the input engine won't function properly If remove this line. I didn't dig in for the reason.

```
g_signal_connect(engine, "process-key-event", G_CALLBACK(engine_process_key_event_cb), NULL);
```

As for the enable listener. It's necessary becase there we'll cache the current enabled engine to use in function "xrdp_input_send_unicode". It's welcome if you have better solutions because again I didn't dig in.

**Comment by JulyIghor** [comment]
I confirm those lines are unused and can be safely removed
```
    g_signal_connect(factory, "enable", G_CALLBACK(xrdp_input_ibus_engine_enable), NULL);
    g_signal_connect(factory, "disable", G_CALLBACK(xrdp_input_ibus_engine_disable), NULL);
```

Also suggested waiting of ibus is not enough, I had to use this to make it failover

```bash
#!/usr/bin/env bash
while ! ibus engine 2>/dev/null; do
    sleep 1
done
```

**Comment by seflerZ** [comment]
@JulyIghor Thanks for feedback. Did you notice we had a var assign in "xrdp_input_ibus_engine_enable" function?

```
static void
xrdp_input_ibus_engine_enable(IBusEngine *engine)
{
    LOG(LOG_LEVEL_INFO, "xrdp_ibus_engine_enable: IM enabled");
    g_engine = engine;
}
```

How can it be triggered if func registration removed?

**Comment by seflerZ** [comment]
@JulyIghor Thanks for feedback. I got your idea. Looks like we had duplicated func registration in line 135 and line 158. I think we can remove those in line 158.

**Comment by matt335672** [comment]
@JulyIghor - where are you adding your bash code exactly?

**Comment by JulyIghor** [comment]
> @JulyIghor - where are you adding your bash code exactly?

My environment is rootless docker container. I am adding this code before I start session manager. I need keyboard to work ASAP as desktop is available. I am sending keys via libfreerdp so I was able to test that well. When IBUS_ADDRESS is available it is still required to wait for original global engine.

**Comment by JulyIghor** [comment]
I noted that pressing Ctrl+S does work to save remotely opened document, but if I keep holding those too long, it starts typing letter S instead of doing nothing. Can anyone please confirm it is the same for everyone?

**Comment by seflerZ** [comment]
> I noted that pressing Ctrl+S does work to save remotely opened document, but if I keep holding those too long, it starts typing letter S instead of doing nothing. Can anyone please confirm it is the same for everyone?

Negative. I'm using Ubuntu 22.04 with Microsoft mstsc.

**Comment by matt335672** [comment]
OK - thanks.

As far as this issue is concerned, I think we're done now. Is that right?

**Comment by seflerZ** [comment]
Yes.
