### ISSUE TITLE
Can't run xrdp on OSX 10.11

### ISSUE THREAD

**Issue by sgdc3** [neutrinolabs/xrdp#520]
I created this script to install xrdp on OSX 10.11 El Capitan:

https://gist.github.com/sgdc3/e870b365dbd060eeb9bd776b4f465d19

It compiles without errors but when i run the xrdp.sh file i get this error:

```
-n Starting: xrdp and sesman . . 
dyld: lazy symbol binding failed: Symbol not found: _OPENSSL_init_ssl
  Referenced from: /usr/lib/xrdp/libcommon.0.dylib
  Expected in: flat namespace

dyld: Symbol not found: _OPENSSL_init_ssl
  Referenced from: /usr/lib/xrdp/libcommon.0.dylib
  Expected in: flat namespace

./xrdp.sh: line 30:  2966 Trace/BPT trap: 5       $SBINDIR/xrdp
.
```

**Comment by proski** [comment]
It's much easier to compile xrdp against openssl from homebrew:
```
brew install openssl
cd xrdp
./bootstrap
./configure PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
make
sudo make install
```
I was able to run `xrdp` and get the greeter, but I have never put any serious effort into running any backend.

**Comment by proski** [comment]
I have verified that xrdp can be build against the current OpenSSL from git. Both xrdp and xrdp-sesman run. I can interact with the login screen. I cannot login because xrdp-sesman cannot authenticate me with PAM - that's an unrelated issue.

The script is invalid. It builds 64-bit OpenSSL and 32-bit xrdp. I suspect xrdp builds against the OpenSSL headers, but runs against Apple SSL, which doesn't export `OPENSSL_init_ssl`

**Comment by sgdc3** [comment]
Thank you! It works now!
One last question: how to fix the issue with PAM? Is there any workaround?

**Comment by proski** [comment]
I tried PAM and Kerberos. Neither works. It needs to be debugged. A dumb workaround would be change the code to authenticate everybody.

But it won't be the last question. Once the authentication works, there would be an issue with the backend. And then with the window manager and so on. So let's resolve this bug and address other issues separately.

**Comment by sgdc3** [comment]
Ok, thank you
