### ISSUE TITLE
Reconnect to old vnc session - VNC password failed

### ISSUE THREAD

**Issue by bin101** [neutrinolabs/xrdp#613]
I build xrdp myself and use the xvnc backend. Since 0.9.1 i cant reconnect to an old session (using the the port which the backend created), always getting "VNC password failed" errors.

This must have something to do with the new way of creating vnc passwords per session and creating them as hashes. I reverted all of these commits but keeping the other stuff which comes with 0.9.1/newer and now it works again.

Maybe related commits:
https://github.com/neutrinolabs/xrdp/pull/558
https://github.com/neutrinolabs/xrdp/pull/523

**Comment by jsorg71** [comment]
So are you using vnc-any or do you let xrdp start vnc?

**Comment by UntilSunrise** [comment]
I am using two profiles to let xrdp start vnc and connect to this created session:

[xrdp0]
name=OldSession
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=5910
delay_ms=5000

[xrdp1]
name=NewSession
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=-1
delay_ms=5000

in combination with MaxSessions=1 in sesman.ini.
I only with this single session.

**Comment by UntilSunrise** [comment]
You can see the full list of reverted commits on my fork (https://github.com/UntilSunrise/xrdp/commits/devel). Anywhere there have to be the issue...

**Comment by jsorg71** [comment]
Oh no, this now does not work by design.  sesman handled vnc sessions use a random password to connect.
Can you remove the first section and only have [xrdp1] ?

**Comment by UntilSunrise** [comment]
If I remove the first section it works if I want to reconnect manually but if I want to autoconnect with given username and password, sesman tries to create a new session instead of reconnecting to the old one:
![image](https://cloud.githubusercontent.com/assets/12427722/21698483/7525e784-d397-11e6-9a08-17dfd40410a5.png)
![image](https://cloud.githubusercontent.com/assets/12427722/21698529/adee5b14-d397-11e6-808f-944d8cb5569c.png)

Remember I set MaxSessions=1 because I only want one single persistent session.

Once autoconnect failed I even arent able to connect manually (with the same error as autoconnect) without restarting xrdp/xrdp-sesman.

**Comment by tenhow** [comment]
Is there any update?

**Comment by tenhow** [comment]
I am curious about this, after suffer two days

**Comment by tenhow** [comment]
same question, @bin101  have you find the version with random password feature not added?

**Comment by tenhow** [comment]
I would like to downgrade to it

**Comment by tenhow** [comment]
@jsorg71  could you help me to find that version with sesman random password feature not added?
