### ISSUE TITLE
CONNECTION_TYPE_AUTODETECT support

### ISSUE THREAD

**Issue by SolalPirelli** [neutrinolabs/xrdp#843]
Hi, and thanks for the amazing work on xrdp. 😄 

It appears that `mstsc` on Windows 10 (or at least, my machine, with my setup, remoting to my client, etc.) sends `7` as the `msc_connection_type`, i.e. `CONNECTION_TYPE_AUTODETECT`.

I don't see any occurrence of that string in the xrdp codebase aside from its declaration, so it seems it's not supported.

This is unfortunate, because `xrdp_encoder_create` returns null if `client_info->mcs_connection_type != CONNECTION_TYPE_LAN`, even though semantically that's wrong with an "auto-detect" flag, so I can't get RemoteFX to work.

Any plans to support the flag?  
If not, could you add some optional bypass for the `mcs_connection_type` check so that the user can say "I know my network can run RemoteFX" ?

**Comment by metalefty** [comment]
Supporting `CONNECTION_TYPE_AUTODETECT(=7)` and enabling RemoteFX when `CONNECTION_TYPE_AUTODETECT` are separate issues.

You cannot use RemoteFX when `connectionType == CONNECTION_TYPE_AUTODETECT` due to protocol specification. xrdp is compliant with this. When `connetionType == autodetect`, xrdp doesn't advertise RemoteFX capability to the client.  Set `connectionType == LAN` if you want to use RemoteFX.

> Furthermore, if the connectionType field of the Client Core Data ([MS-RDPBCGR] section 2.2.1.3.2) is set to any value other than CONNECTION_TYPE_LAN (0x06), then the RemoteFX server SHOULD NOT<2> indicate that the RemoteFX codec is supported

https://msdn.microsoft.com/en-us/library/ff635369.aspx

You can change the code and bypass `mcs_connection_type` check but it will lose client compatibility. Windows Remote Desktop client can connect but MS official Mac client shows a blank screen.

**Comment by SolalPirelli** [comment]
Hmm, it seems the protocol is surprisingly silent about `AUTODETECT`, there are only 2 instances of that word on msdn.microsoft.com according to Google. Oh well, if the Mac client crashes by changing this, I guess I'll just patch my xrdp locally... Thanks for the quick answer!

**Comment by metalefty** [comment]
Just FYI, Windows to Windows (8 or later) remote desktop can use RemoteFX with `AUTODETECT` or else connection types. MS calls it "RemoteFX on WAN". It can be called 2nd generation RemoteFX not an official name though. xrdp only supports 1st generation RemoteFX introduced in Windows 7 (RDP 7.1). RDP 7.1 RemoteFX is `connectionType = LAN` only.
https://blogs.technet.microsoft.com/enterprisemobility/2012/08/23/remotefx-for-wan-overview-of-intelligent-and-adaptive-transports-in-windows-8-and-windows-server-2012/

If we implement 2nd gen RemoteFX, RemoteFX can be used via any connection type.
