### ISSUE TITLE
[Question]  user and mulitple sessions

### ISSUE THREAD

**Issue by choman** [neutrinolabs/xrdp#907]
First I love where this project is at, you guys are rocking it.

I have a unique case and cannot find any info on if it is possible or not.

I am on a centos 7.4 system pulling xrdp .9.3 from epel.  I have a case where 
I need users to be able to obtain more than one session.

To be clear, I am not talking multiuser support.  nor Iam I talking session sharing.
but rather multisession support per user.

e.g. 
if I have a user bob running rdesktop, I'd like hime to be able to 
  rdesktop -u bob <xrdp>  --> run firefox in fullscreen 
  rdesktop -u bob <xrdp> --> run libreoffice in fullscreen 

Is this currently possible?  If not, is it on the roadmap?

Thanks again

**Comment by metalefty** [comment]
I assume you're using xorgxrdp backend. That is possible but there's some side effect.
See `Policy` parameter in `sesman.ini`.  It can configure session allocation policy.
`Policy=UBC` or `Policy=UBDC` should make it possible what you want.

The side effect is bob cannot connect existing session once disconnected because there's no feature to choose a session from multiple existing sessions. New connection always creates a new session. This will cause session/resource exhaustion but at least you can have multiple sessions per one user.

**Comment by purvalpatel** [comment]
@metalefty  it works using UBDC option.

**Comment by choman** [comment]
i'll have to double check my backend, I know I'm installing xorgxrdp and tigervnc.   is there an easy way to check?  I'm pretty sure I'm using xorgxrdp, but the end process I know is Xvnc,   Guess I'm not too familiar with how the back-end frameworks work together

Also, how do I disable mirroring sessions.  
- If I rdesktop to bob and disconnect. I reconnect which is awesome.
- but if I rdesktop to bob and then rdesktop again to bob I get two identical sessions  that mirror each other

**Comment by mailinglists35** [comment]
> there's no feature to choose a session from multiple existing sessions yet

where can I watch for progress on this feature? it would be very useful. thank you!
